### ISSUE TITLE
Add a feedback box for the profiles search

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#1018]
* An example of the functionality can be found here - https://optimus.foundation/en/projects/13/ (The email notification isn't necessary for now, as well as the up/down buttons.)
* Only to be added to eahub.org/profiles
* Data should be saved in django model
  * Store page url, too. Atm, this will only be /profiles, but we'd like it to be extandable for the future
* Data should be exportable from admin panel
* I would recommend a bootstrap4 modal window with email (optional) and message (multiline, required) field.
* On mobile perhaps it can be reduced in size compared to the optimus.foundation version?
* Feedback button should fit with eahub's color scheme

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199881547599376) by [Unito](https://www.unito.io/learn-more)

**Comment by sebgrebe** [comment]
Where should the feedback be sent to/saved?

**Comment by sebgrebe** [comment]
And did we decide whether we want to have it on all pages or just on the profiles page?

**Comment by victor-yunenko** [comment]
> Where should the feedback be sent to/saved? @victor-yunenko

I would create a simple django model with the aforementioned fields

**Comment by sebgrebe** [comment]
> 
> 
> > Where should the feedback be sent to/saved? @victor-yunenko
> 
> I would create a simple django model with the aforementioned fields

How would we then get this into a format that Vaidehi can access this? Import from the admin panel? So would we have to add this to?
Or might it be simpler to link the form to a google form, so that Vaidehi can access the feedback there? (I haven't done this before, but I could imagine that there is a way to integrate html forms with google forms

**Comment by victor-yunenko** [comment]
Ideally on every page, although since the old pages use bs3 at the moment, we might limit ourselves to the profiles page. Bs5 is just friendlier in terms of modals... and everything else :)

**Comment by sebgrebe** [comment]
> 
> 
> Ideally on every page, although since the old pages use bs3 at the moment, we might limit ourselves to the profiles page. Bs5 is just friendlier in terms of modals... and everything else :)

OK, let's stick with profiles page then

**Comment by sebgrebe** [comment]
Oh, but I guess that means that we can't work on this before the new profiles page is in.

**Comment by victor-yunenko** [comment]
> How would we then get this into a format that Vaidehi can access this? Import from the admin panel? So would we have to add this to?

I would say as any django model, eg:

![image](https://user-images.githubusercontent.com/36416236/100549164-f3581600-3279-11eb-94b8-de998fa239ef.png)

**Comment by victor-yunenko** [comment]
> Oh, but I guess that means that we can't work on this before the new profiles page is in.

I think merging into `divio` sounds ok to me

**Comment by sebgrebe** [comment]
I've updated your comment on the requirements
