### ISSUE TITLE
Refresh on eahub.org/profiles generates increasing pagination

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#1034]
When you refresh the page eahub.org/profiles (with out without a customer filter) then the pagination increases e.g.:

https://eahub.org/profiles/?page=2
https://eahub.org/profiles/?page=3

etc. 

or
https://eahub.org/profiles/?query=gary
https://eahub.org/profiles/?query=gary&page=2

etc.

**Comment by victor-yunenko** [comment]
Another solution might be to do only one query and then show it incrementally, as the official docs suggesting - https://www.algolia.com/doc/guides/building-search-ui/ui-and-ux-patterns/infinite-scroll/vue/
