### ISSUE TITLE
The new fider (feedback.eahub.org) instance is hosted for free but needs manual weekly/monthly backups

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#1087]
https://control.divio.com/control/71735/edit/88703/backups/

**Comment by victor-yunenko** [comment]
cc @sebgrebe

**Comment by victor-yunenko** [comment]
Hi @sebgrebe, maybe if you're doing it every once in a while for eahub you could also do eg a monthly export of the feeder backups?

**Comment by sebgrebe** [comment]
@victor-yunenko, sure, updated the google event
