### ISSUE TITLE
Drop the email confirmation page - config the email by just clicking on the link (it's a standard allauth feature)

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#1103]
When you sign up you receive the confirmation email, the link in it requires a button click, which I don't think we need. The button is also not styled.

https://eahub-stage.us.aldryn.io/accounts/confirm-email/MjIzODY:1kyaTP:egdZY0nAK-1Na1i8zD-fo7OlhQA/

![image](https://user-images.githubusercontent.com/36416236/104123985-0fa1a500-5346-11eb-9e83-ce114ae0ab5e.png)

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199881534369863) by [Unito](https://www.unito.io/learn-more)

**Comment by viktor-yunenko** [comment]
it was done
