### ISSUE TITLE
User registration - add a screening question that would filter out spam users

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#1118]
### Current state
It can be difficult for admins to distinguish bots and spam users from genuine users

### Desired state
* Add Approval question to sign up page: “What does Effective Altruism mean to you?”
* Info text: (grayed out) This question is to ensure that all users of the EA Hub are here because of their interest in Effective Altruism. Your answer won't be made public. 
* Show anser in user admin panel as column to make approval process easier for admins

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199888566999783) by [Unito](https://www.unito.io/learn-more)

**Comment by sebgrebe** [comment]
And show in user admin panel as column to make approval process easier for admins

**Comment by sebgrebe** [comment]
Email verification solved this problem mostly, so no need anymore
