### ISSUE TITLE
Allow users to be only internally visible

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#1120]
dropdown

* public
* internal - for eahub users
* private

the last option could be visible only to the current private users

tasks

* create another algolia index
* register Profile model in both indexes, test the indexing on internal & public updates
* rename algolia indexes to something as `profiles_public_prod` and `profiles_internal_prod`
* the algolia indexes could use different `should_index` methods, eg as `is_searchable_public`/`is_searchable_internal`
* profiles search would use different indexes based on the user session
* the homepage could simply hide the internal profiles on the map for simplicity sake
* the group detail page could hide the internal profiles for simplicity sake

**Comment by vagarwalla** [comment]
mildly related #1092

**Comment by sebgrebe** [comment]
Implemented
