### ISSUE TITLE
Request Algolia open source subscription tier again

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#1155]
┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199935813393716) by [Unito](https://www.unito.io/learn-more)

**Comment by victor-yunenko** [comment]
Just sent:

> Greetings!
> 
> We've been working on an MIT licensed community project for Effective Altruism community (effective-altruism.org). We're big fans of aloglia and actively using it on the profiles directory page with your amazing vuejs integration - https://eahub.org/profiles/
> 
> And in my free time I've implemented and now maintaining a FOSS djangocms-algolia integration package for https://github.com/django-cms/django-cms community.
> 
> If you could consider helping us with an open-source subscription we would warmly appreciate it!
> 
> All the best,
> Victor

**Comment by viktor-yunenko** [comment]
a sponosred approved
