### ISSUE TITLE
Docker-Compose 3.0 "Extends" functionality removed: "docker-compose run" won't work until rewritten without using extends

### ISSUE THREAD

**Issue by walambert** [rtcharity/eahub.org#1169]
Current version of docker-compose.yml in use makes load-bearing use of extends. Support for extends was removed as of docker-compose version 3, our compose file is version 3.4. 

I believe this is why docker-compose run... is failing.

See "Removed" from Version 3: https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-versioning.md#version-3

Unfortunately, the reference specifications for compose to not make a note that extends was deprecated as of 3.0 (https://github.com/docker/docker.github.io/blob/master/compose/compose-file/compose-versioning.md).

**Comment by viktor-yunenko** [comment]
Thank you for the ticket! I updated the versions for now, in the feature I'm planning to move away from selenium, and could address the source of the problem during that task.
