### ISSUE TITLE
GDPR compliance: remove the cookie bar and add a privacy policy agreement

### ISSUE THREAD

**Issue by viktor-yunenko** [rtcharity/eahub.org#1175]
At the moment our cookie bar isn't GDPR-compliant and it isn't needed, because we don't collect private data of non-logged-in users. And the cookie bar isn't helping our UX efforts :)

Yet we do collect the private data of registered users without an explicitly given consent to our privacy policy.

FYI a GDPR-compliant cookie bar specification that we don't have - and don't need:

* analytics must not be enabled without an explicit consent
* analytics must be disablable
* after giving consent the user must be able to disable the analytics later at any point of time

But we don't need a cookie bar because we don't collect identifiable data of anonymous users, eg as IPs.

What we must have though is an agreement to our privacy policy on all signup forms. I propose a simplified version as a text label:

> By signing up you're agreeing to our Privacy Policy

**Comment by viktor-yunenko** [comment]
@sebgrebe, ok for you?

**Comment by sebgrebe** [comment]
### Acceptance criteria  
- [ ] On the signup form, a checkbox with the text "I agree to the EA Hub's Privacy Policy [link]" is present and checked
- [ ] Text is the same height as current privacy policy link (.9 rem) and
- [ ] the checkbox has `required` attributed set
- [ ] Present on sign up forms on homepage and /accounts/signup/


```
    display: flex;
    margin-top: 1rem;
    margin-left: 11px;
    color: #5d5d5d;
```

**Comment by viktor-yunenko** [comment]
FYI, no backend logic is needed, only html

**Comment by sebgrebe** [comment]
Legal situation seems unclear: https://law.stackexchange.com/a/35587.

**Comment by viktor-yunenko** [comment]
I just noticed that SO is the first site that I saw with an adequate GDPR banner:

![image](https://user-images.githubusercontent.com/36416236/114267805-ca991780-99f5-11eb-9973-e5d70dcb5b19.png)

Let's mimic that if we're going to keep the bar.

**Comment by sebgrebe** [comment]
We want to use this package: https://gitlab.com/what-digital/django-privacy-mgmt
