### ISSUE TITLE
Move Privacy Policy page to bootstrap 5

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#1186]
### Current state
* On some pages we use bootstrap 3, on some bootstrap 5. We want all on 5
* Privacy policy oage is still on bootstrap 3

### Desired state
* Provacy policy page uses bootstrap 5: https://eahub.org/privacy-policy/
* Example of page that has already bootstrap 5: https://eahub-stage.us.aldryn.io/about/

### Acceptance criteria
* [ ] Privacy policy page uses bootstrap 5

**Comment by viktor-yunenko** [comment]
That was done
