### ISSUE TITLE
Display user's location on profile page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#1241]
Currently missing. We have the local group membership, but (1) someone might not have added this or (2) live somewhere else than to which group they might feel the most attached or (3) the group might not be a city-based group.

![image](https://user-images.githubusercontent.com/15908208/114297104-ac3f2480-9aa6-11eb-9a9b-6122d206c135.png)

**Comment by viktor-yunenko** [comment]
True, I created an extended ticket a few days ago, that also includes the search #1238.

I'll close this one for now then if you don't mind. Please feel free to reopen if needed.
