### ISSUE TITLE
Multiple groups directory bugs (may be related, otherwise feel free to split to many issues) 

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#1264]
@victor-yunenko 

* [ ] Even though it shows USER as an organiser of GROUP on their profile , it doesn't show on the GROUP page. I expect this happened after the change to allow non-Hub users be listed as organisers
* [x] The GROUP Meetup link was not working When I went to check the status it was listed as active but not public. Link was showing page does not exist. 
* [ ] USER's profile is still linked to the GROUP group. I went and made the group "inactive" but it has not removed it from their profile
* [ ] I cannot link existing users to group via the admin panel (both when I go to edit the group AND when I go to edit the profile). I'd like to have this functionality.

**Comment by sebgrebe** [comment]
> The GROUP Meetup link was not working. When I went to check the status it was listed as active but not public. Link was showing page does not exist.  

This is desired behaviour

**Comment by sebgrebe** [comment]
Created new ticket for admin panel functionality as this is not a bug: https://github.com/rtcharity/eahub.org/issues/1272
