### ISSUE TITLE
Request failed with status code 400 when I try to add Cause Areas of Interest from listed options

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#1265]
Filed by Tessa Alexanian on 18 May 2021. Original email: 

> 
> Wanted to report a bug (see title, and hopefully this screenshot comes through):
> image.png
> 
![image](https://user-images.githubusercontent.com/32846756/118604218-7ac52180-b7e7-11eb-8d8b-1122a8b8d4cf.png)

**Comment by vagarwalla** [comment]
Mentioned by another person: 
![image](https://user-images.githubusercontent.com/32846756/119077837-a2a2c800-ba27-11eb-8197-ce0719df82e9.png)


I was able to recreate the error on my account.

**Comment by vagarwalla** [comment]
Steps to reproduce problem - Using Google Chrome on Microsoft Surfacebook 

1. Log in to EA Hub profile
2. Click edit profile
3. In the "career area of interest" Type the word "research" (have to type the whole thing, the word tag "research" doesn't appear before then - it just shows other research. 
4. The error code screenshotted below appears. 
![image](https://user-images.githubusercontent.com/32846756/119263306-17852600-bc11-11eb-9aee-76acb165cf30.png)


**Where else does this error appear for the label "research"?**
Error is NOT duplicated for "Career Area of Expertise" (I had research listed before, then removed it, then added it again with no issues. See SS: 

![image](https://user-images.githubusercontent.com/32846756/119263460-b1e56980-bc11-11eb-8fa5-089dd91222c7.png)

Error is duplicated for "Career area of interest" and "Career area of expertise". 


**Other issues - Tags appear to be case sensitive**

Note that for some reason the tags appear to be case sensitive - there is both "research" and "Research". Am not sure why, see SS:
![image](https://user-images.githubusercontent.com/32846756/119263379-6763ed00-bc11-11eb-80dc-e0666adc99a5.png)

But, in Career Area of Interest there is only lowercase "research"
![image](https://user-images.githubusercontent.com/32846756/119263443-a2feb700-bc11-11eb-969b-c6423f89bd33.png)

**Do we need to do a cleanup of the tags? Or can we just change the rule so that tags are not case sensitive?**


**Other issues with the tags - tags appearing in the wrong places.** 

- I'm concerned the tags are all getting mixed up. Note that the organisation names are coming under the Career Area of Expertise tag. Related to #1269 
![image](https://user-images.githubusercontent.com/32846756/119263498-e2c59e80-bc11-11eb-8910-1a3f23601bbf.png)
Also see that software engineering is appearing under "Cause Areas of Interest"
![image](https://user-images.githubusercontent.com/32846756/119263558-1a344b00-bc12-11eb-845d-72208649bc15.png)

**Comment by sebgrebe** [comment]
* @victor-yunenko and I just both followed the steps and could not reproduce it.
* Victor added logging on this action. Next time this happens, we can investigate what's going on.

**Comment by viktor-yunenko** [comment]
With the additional logging we found the problem at patched it today.
