### ISSUE TITLE
Switch the production profile algolia indexes to `_prod` instead of `_stage`

### ISSUE THREAD

**Issue by viktor-yunenko** [rtcharity/eahub.org#1270]
switch the evn vars, because right now most likely the default is used, ie stage. Because we have new variable names?

**Comment by sebgrebe** [comment]
- Added internal index for prod
- Updated env variables on stage and prod to set indices for internal and public, respectively  

QA: 
- Changed my profile on prod, both in public and internal mode, and checked that the prod indices, but not the stage, one changed. 
- Checked whether changes occur correctly on /profiles
- Did the same vice versa for stage
