### ISSUE TITLE
Google Maps API Key Missing?

### ISSUE THREAD

**Issue by taoroalin** [rtcharity/eahub.org#1277]
The Maps panel in the production website is greyed out and says "This page didn't load Google Maps correctly. See the JavaScript console for technical details." 

The console says "Google Maps JavaScript API error: InvalidKeyMapError". Documentation on this error:
https://developers.google.com/maps/documentation/javascript/error-messages#invalid-key-map-error

>The API key included in the script element that loads the API is not found. Please make sure you are using a correct API key. You can generate a new API key in the Cloud Console.

Don't know what caused this, maybe Google Maps just started requiring a key for part of their API, or maybe the calling code has a bug, or something?

**Comment by viktor-yunenko** [comment]
Thank you for the report! I suspect something might have happened to the google maps key.

@sebgrebe said that he'll look into the key status.

**Comment by viktor-yunenko** [comment]
It has been patched, thank you @sebgrebe!
