### ISSUE TITLE
Ability for users to claim group as their own

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#149]
# Problem
- Currently if you are the organiser of `EA London` however aren't marked as it, there's no way of claiming it as my own.

# Solution
- On the group profile page add a `claim this group` button where users can request to be added as an organiser to the group in question.
- The backend then emails `admin@eahub.org` & any other organisers of that group to confirm adding the user as an organiser of the group.
- Once someone grants access an email is sent out to the user telling them `hey your request to be an organiser of EA London has been granted`

**Comment by piotr-asdf** [comment]
To expand this, if a group organiser account is deleted(as made available after GDPR), the group has no organisers and is uneditable by end-user

**Comment by Manoj-nathwani** [comment]
@piotr-asdf yep that's correct

**Comment by Manoj-nathwani** [comment]
@piotr-asdf yep that's correct. Sorry for the late reply!

**Comment by michaltrzesimiech** [comment]
Somewhat related: https://github.com/rtcharity/hubreboot/issues/83

**Comment by michaltrzesimiech** [comment]
It would be ideal to fix this before launch, but it's ok if we won't make it

**Comment by Manoj-nathwani** [comment]
Yeah we're not going to have time, but this and https://github.com/rtcharity/hubreboot/issues/83 will be done asap soon after

**Comment by sebgrebe** [comment]
Happy to work on the frontend part of this, but I'd need some help (or directions) how to implement sending the email - this is a backend task

**Comment by taymonbeal** [comment]
How sad would people be if this were a manual process at first? I.e., we'd have an "I organize this group" button for orphan groups that would send an email to the admins, but from there we'd respond to it manually. This would be very quick to implement.

**Comment by michaltrzesimiech** [comment]
> How sad would people be if this were a manual process at first? I.e., we'd have an "I organize this group" button for orphan groups that would send an email to the admins, but from there we'd respond to it manually. This would be very quick to implement.

That's a great solution to start with!

**Comment by sebgrebe** [comment]
Starting to work on this

**Comment by sebgrebe** [comment]
Implemented this, flow looks as follows:
![screen shot 2019-03-03 at 17 27 40](https://user-images.githubusercontent.com/15908208/53698817-bb3c4e80-3dd9-11e9-8d13-355c96c97e01.png)
![screen shot 2019-03-03 at 17 27 46](https://user-images.githubusercontent.com/15908208/53698819-bd9ea880-3dd9-11e9-83f0-eef5fd770b5a.png)
![screen shot 2019-03-03 at 17 27 57](https://user-images.githubusercontent.com/15908208/53698821-bf686c00-3dd9-11e9-85fb-4d6f99b57954.png)
![screen shot 2019-03-03 at 17 28 04](https://user-images.githubusercontent.com/15908208/53698823-c1cac600-3dd9-11e9-93e6-ffde531f2227.png)

**Comment by taymonbeal** [comment]
As mentioned in the PR, I don't feel that separate pages are needed for this.

**Comment by Richenda** [comment]
That looks good to me @sebgrebe 
Just mentioning that I suggested something related to this in here: https://github.com/rtcharity/eahub.org/issues/278#issuecomment-469452655
