### ISSUE TITLE
Send email to nonexistent accounts on password reset

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#157]

**Comment by sebgrebe** [comment]
![screen shot 2019-01-30 at 07 59 34](https://user-images.githubusercontent.com/15908208/51966677-05da4c00-2465-11e9-83cb-f73d3e0a1540.png)

**Comment by sebgrebe** [comment]
@michaltrzesimiech Done. Nothing fancy. If you

**Comment by piotr-asdf** [comment]
After giving a fake or not used (in account creation) email, password reset site still reports sending an email

**Comment by taymonbeal** [comment]
That's actually a desirable security behavior. Without it, anyone can find out whether any given email address is associated with an account. Of course, it'd be better to _actually_ send an email in that case explaining the situation.

**Comment by sebgrebe** [comment]
I assume we can close this?

**Comment by taymonbeal** [comment]
We should still change the email behavior.

**Comment by taymonbeal** [comment]
But it sounds like there's no more UX work to be done here?

**Comment by sebgrebe** [comment]
> But it sounds like there's no more UX work to be done here?

Not that I'm aware. I did add some layouting

**Comment by sebgrebe** [comment]
> We should still change the email behavior.

I thought you said it's desirable that the page says that the password reset site says email was sent even if account with that email doesn't exist?

**Comment by taymonbeal** [comment]
Yeah, but right now it doesn't actually send it.

**Comment by taymonbeal** [comment]
I would argue that this needs to be fixed by launch. There are going to be a lot of password resets by confused users and we do _not_ want them disappearing into black holes.

**Comment by taymonbeal** [comment]
We wound up deciding that it's okay to disclose whether someone has an account, as long as we send an email to alert users of this.
