### ISSUE TITLE
Python ipdb package no longer works

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#159]
# Problem
- Originally we had ipdb working by running `docker-compose run --service-ports web` however since recent infrastructure updates it no longer works as the command causes issues with outdated migrations.

**Comment by michaltrzesimiech** [comment]
Is this a blocker for us @Manoj-nathwani @taymonbeal ?

**Comment by taymonbeal** [comment]
No.

**Comment by Manoj-nathwani** [comment]
No, it's just a nice-to-have as we're now cowboys writing code and hoping for the best, ratehr than being able to test locally in a nice way 😅

**Comment by patbl** [comment]
#846 has instructions for getting the debugger working. Do you think that's sufficient to close this issue?

**Comment by victor-yunenko** [comment]
Let's close it for now, if #846 doesn't help we can figure it out there.
