### ISSUE TITLE
Error handling typos in location data

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#161]
# Problem
- We're not handling location errors when users may input a typo in the `town_or_city` or `country` fields when editing a group or their profile
- This causes bad data in our database & either groups or profiles not showing up on the map

# Solution
- As `lat/lon` is automatically generated on the backend using the `town_or_city` and `country`, we can automatically detect errors as it would fail finding a valid lat/lon. In that case we should flag it somehow to the user so they can fix it for us. This way we can get users to fix validation issues with their data rather than having to manually fix it ourselves.

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech, does this seem like a good solution?

**Comment by michaltrzesimiech** [comment]
Definitely go for it! Bonus points if we could send a notification to ourselves as well (in case user input is correct, but our thing fails for no clear reason).

**Comment by michaltrzesimiech** [comment]
https://github.com/rtcharity/hubreboot/issues/129

**Comment by Manoj-nathwani** [comment]
Changing priority as it's not something we need to sort out urgently

**Comment by victor-yunenko** [comment]
@sebgrebe, it sounds as it could be resolved through #72, do you think we should merge those two tickets?
