### ISSUE TITLE
Get rid of "via sendgrid.net" on emails

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#163]
This should just be a matter of DNS and SendGrid configuration.

**Comment by taymonbeal** [comment]
Okay, does anybody know who has access to the SendGrid password? @michaltrzesimiech? @Manoj-nathwani? @jpzg?

**Comment by Manoj-nathwani** [comment]
Password is on lastpass:
![image](https://user-images.githubusercontent.com/2634482/54406265-5e636100-4714-11e9-86f3-f458b28c5dbf.png)

Just tried viewing the password within lastpass and it's giving me `This is a shared site. You are not permitted to view the password.` So i guess you'll need to get lastpass configured if you haven't already

**Comment by Manoj-nathwani** [comment]
You're probably looking to do this: https://sendgrid.com/docs/ui/account-and-settings/how-to-set-up-domain-authentication/

**Comment by taymonbeal** [comment]
I'm not sure what you mean by "get LastPass configured". I assume that only the person who entered this password can view it.

**Comment by Manoj-nathwani** [comment]
That was me however i'm unable to see the password as it's part of the rethink org.

"get LastPass configured" --> install lastpass and use it to log into sendgrid

**Comment by taymonbeal** [comment]
Putting this on hold until we figure out our emailing-people strategy, because we might need to ditch this SendGrid account anyway for one through Azure that offers better pricing.

**Comment by michaltrzesimiech** [comment]
It must be Manoj.

⁣Sent from BlueMail ​

**Comment by michaltrzesimiech** [comment]
SendGrid will cost us $15/mo. Should I pay for it right now, which will also presumably remove the "sent via SendGrid" phrase?

**Comment by taymonbeal** [comment]
Wait, I'm confused what you mean. We already have a SendGrid account, and getting rid of "sent via SendGrid" is a matter of fixing our DNS, not paying more money.

**Comment by taymonbeal** [comment]
Planning to fix this as part of #473.

**Comment by taymonbeal** [comment]
No longer seeing this in Gmail.
