### ISSUE TITLE
Consider minor post-release upgrades based on testing

### ISSUE THREAD

**Issue by marcinkowrygo** [rtcharity/eahub.org#178]
https://docs.google.com/spreadsheets/d/1qotdbleP9NHHieVsFkO2LQ6qeI43wBF2P0m_2NOe-xw/edit#gid=0

**Comment by michaltrzesimiech** [comment]
Let's run each of each of these points through @Richenda before implementing, please.

**Comment by Richenda** [comment]
I just took a look again. Was there anything which changed after I added comments to the sheet? Because if not, then I think it's already clear there which ones have the green light!

**Comment by marcinkowrygo** [comment]
@Richenda There's nothing new (besides 52/53, which are minor things suitable for later upgrades).

**Comment by marcinkowrygo** [comment]
15 new issues (points 57-71) after re-testing, with 7 assigned a high priority (P2).

**Comment by Richenda** [comment]
Okie doke!

**Comment by Richenda** [comment]
@marcinkowrygo @sebgrebe 
I once more added my comments in Column C. Thanks!
