### ISSUE TITLE
Profile picture update: handling non-picture files

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#211]
When inadvertently uploading a pdf file, site throws an error

**Comment by sebgrebe** [comment]
![screen shot 2019-02-06 at 20 49 25](https://user-images.githubusercontent.com/15908208/52372716-c907e980-2a50-11e9-97e4-546d29af091e.png)

**Comment by taymonbeal** [comment]
This isn't really enough data to tell what went wrong. Can we maybe turn off DEBUG in order to get more informative stack traces by email?

**Comment by Manoj-nathwani** [comment]
# New error after changing `Debug=False`
![image](https://user-images.githubusercontent.com/2634482/52390891-50933e00-2acd-11e9-906e-01c2b9a6dff1.png)


Where do the emails go? Can we set up some kinda logging service

**Comment by taymonbeal** [comment]
They go to the ADMIN email address.

**Comment by david-mears** [comment]
This seems to be fixed? When I run locally and upload a .pdf or a .exe:

<img width="310" alt="valid_image" src="https://user-images.githubusercontent.com/44967334/59804168-70d9d180-92e5-11e9-9bf2-6b32c40cc758.png">

**Comment by michaltrzesimiech** [comment]
Closing as implemented
