### ISSUE TITLE
Edit/message buttons: not working when navbar-menu pulled out.

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#212]
Should have been fixed by z-index, but it's not.

**Comment by sebgrebe** [comment]
Only works when not logged in (because menu is shorter than). This is an annoyingly stubborn problem!

**Comment by michaltrzesimiech** [comment]
I think it's fair to set a budget for it exceeding of which will push the priority of this further down into a future release Seb

**Comment by taymonbeal** [comment]
This has exceeded its engineering time budget, so I'm moving it to Plato.
