### ISSUE TITLE
Frontend JavaScript unit tests

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#226]
We need to add tests both for the frontend JS as well as end-to-end integration tests to increase stability of app and make further development easier and safer. 
Possible testing frameworks: jasmine for unit tests, Selenium for integration tests

**Comment by sebgrebe** [comment]
There is already a ticket for integration tests #165.
Depending on what we use for this, we might use the same framework for unit tests. For example, if we were to go with pupeteer and jest for integration tests (as [proposed by me](https://github.com/rtcharity/hubreboot/issues/165#issuecomment-465077169)), we could use jest for unit tests as well.

It seems to me that integration tests should have priority over frontend unit tests.

**Comment by taymonbeal** [comment]
Blocked by #349.
