### ISSUE TITLE
Use Django forms for rendering

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#229]
See, e.g., https://docs.djangoproject.com/en/2.1/topics/forms/

This will make it possible to change the workings of models without writing a bunch more HTML.

django-crispy-forms is probably the easiest way to integrate this with Bootstrap.

**Comment by sebgrebe** [comment]
This has been partly addressed [in this PR](https://github.com/rtcharity/eahub.org/pull/346).
After this PR, I believe whenever we implemented forms we tried to use django forms wherever that was easily possible.
@taymonbeal Do you think it's still necessary to go through all forms and try to decrease the use of customised solutions?

**Comment by taymonbeal** [comment]
Yes, I think we should figure out definitively what the most idiomatic and maintainable way to specify forms in Crispy is, and then do that everywhere. Like, I think it has some facilities to specify forms in the Django code instead of mucking around with templates.

**Comment by taymonbeal** [comment]
@sebgrebe, do you need my help in continuing this?

**Comment by victor-yunenko** [comment]
We're planning a soft redesign in the future, during which the forms would definitely be updated, hence I guess we can close this ticket for now? Please feel free to reopen if needed.
