### ISSUE TITLE
Add an option to remove profile picture

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#255]

**Comment by michaltrzesimiech** [comment]
@Richenda how should this work? I.e. where a button to delete the profile picture should be placed?

**Comment by Richenda** [comment]
That's a good call. Currently if you don't like what you've got, you have to put a different image up. This might be a pain for some users. I think addition of 'delete image' would be good, but then it would default to one of the randomly allocated images.

**Comment by Richenda** [comment]
I think this can be moved to Plato or later, tbh.

**Comment by taymonbeal** [comment]
Yeah, I had been worried about the privacy implications, but there's nothing stopping someone from uploading a generic-looking profile picture to replace one they want to get rid of.

**Comment by michaltrzesimiech** [comment]
Closing as implemented
