### ISSUE TITLE
Non-SSL links without warning list

### ISSUE THREAD

**Issue by piotr-asdf** [rtcharity/eahub.org#277]
Apart from already fixed eawork.club there are couple other sites that link to http instead of https, if they don't have SSL certificate a warning could be considered, here's the list:
-linking from https://staging.eahub.org/privacy-policy/ to http://www.allaboutcookies.org is https -> http transition without warning, same with http://optout.aboutads.info/?c=2&lang=EN
- http://priority.wiki
- http://effectivethesis.com

**Comment by taymonbeal** [comment]
I'm not convinced that warnings beyond what the browser provides are actually useful. More useful would be to get those sites to switch to HTTPS. To the extent that that's not practical, we can just link to the insecure HTTP links.

**Comment by sebgrebe** [comment]
so should we close this?

**Comment by taymonbeal** [comment]
priority.wiki does actually support HTTPS, so we should change the link to reflect this.

Do you know who runs effectivethesis.com?

**Comment by sebgrebe** [comment]
> Do you know who runs effectivethesis.com?

I don't. I think the others might. @Richenda ?

**Comment by Richenda** [comment]
David Janku

**Comment by michaltrzesimiech** [comment]
david.janku@efektivni-altruismus.cz

**Comment by taymonbeal** [comment]
Is anyone in a position to reach out to him?

**Comment by michaltrzesimiech** [comment]
I will

**Comment by michaltrzesimiech** [comment]
Reached out

**Comment by michaltrzesimiech** [comment]
![image](https://user-images.githubusercontent.com/14195560/75868619-99204680-5e08-11ea-8c03-893d6e4c38ae.png)
