### ISSUE TITLE
Make "inactive" groups visually distinct on the map

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#278]

**Comment by sebgrebe** [comment]
Started to work on this. Should this status be true or false by default? Will we set the status or will we write to groups asking them to set this status?

**Comment by sebgrebe** [comment]
![screen shot 2019-03-02 at 15 34 43](https://user-images.githubusercontent.com/15908208/53684102-e737d100-3d00-11e9-8a25-766281655db9.png)
I've implemented this by making inactive groups' markers pale. @Richenda does this look of for you? (not on actual page yet, hence the screenshot)

**Comment by sebgrebe** [comment]
We also need to communicate this on the group's page itself somehow. Any UX proposals @Richenda?
Where would you put the inactivity-status on a page like this? I feel like just putting it under Key Facts might not be sufficiently prominent

![screen shot 2019-03-02 at 15 43 12](https://user-images.githubusercontent.com/15908208/53684168-f5d2b800-3d01-11e9-9e84-5bd0c5d78328.png)
![screen shot 2019-03-02 at 15 43 00](https://user-images.githubusercontent.com/15908208/53684169-f5d2b800-3d01-11e9-84d4-5cafb70d180f.png)

**Comment by taymonbeal** [comment]
We already know whether the groups in the Airtable are active or not; that information can be imported when we redo the migration. New groups should presumably be required to specify whether they're active or not; we can have a checkbox in the form.

**Comment by michaltrzesimiech** [comment]
> Started to work on this. Should this status be true or false by default? Will we set the status or will we write to groups asking them to set this status?

All of the groups we imported we currently believe to be active. Pale markers look great, Seb. I think we should add that info to Key Facts. 

I'm unsure whether we should add the possibly to offer a comment to why/how is a group inactive, but that doesn't strike me as a priority for now.

**Comment by Richenda** [comment]
>I've implemented this by making inactive groups' markers pale. @Richenda does this look OK for you? (not on actual page yet, hence the screenshot)
The pale markers look awesome @sebgrebe  
I agree with Michal that it's not an immediate priority to decide the issue of how much info users give us on group activity. For now, what we need is a general button on a group profile that logged in users can all access which allows a person to submit new information about that group. I saw this on the Hub recently but I can't see it there now? Right now I'm logged in and don't see 'Claim a group' on group profiles? Where did that go? Anyhow wherever 'claim a group' is we should also have 'submit an update about this group'. We can send that to a google form and then that gets premoderated by LEAN who change the profile if they trust the source.

**Comment by sebgrebe** [comment]
> Right now I'm logged in and don't see 'Claim a group' on group profiles? Where did that go? 

This is done, but still in code review. Should be ready tomorrow

**Comment by sebgrebe** [comment]
>  Anyhow wherever 'claim a group' is we should also have 'submit an update about this group'. 

[There is a ticket for this now](https://github.com/rtcharity/eahub.org/issues/308)

I'll try to do this tomorrow. .
