### ISSUE TITLE
Change the privacy note in /profile/signup/

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#279]
Currently: 

> Note: Once you have signed up, your name will be public on the Hub. Read more about our privacy policy.

Desired:

> Note: Once you have signed up, your name and other information will become public. Read more about our approach to privacy in our Privacy Policy.

**Comment by sebgrebe** [comment]
> Note: Once you have signed up, your name and other information will become public. Read more about our approach to privacy in our Privacy Policy.

That's technically not correct. On sign up, the only information that is made public is their name. However, at every other point where they can update profile information they're warned that it's made public - so we should be covered?

**Comment by sebgrebe** [comment]
@michaltrzesimiech would you be happy with leaving it as it is? Or do you want me to change it?

**Comment by michaltrzesimiech** [comment]
Sure, let's leave out the "other information" out, but add a bit more polish:

> Note: Once you have signed up, your name will be publicly displayed on the Effective Altruism Hub. Read more about our approach to privacy in our Privacy Policy.

**Comment by sebgrebe** [comment]
made a PR
