### ISSUE TITLE
Should the "Community" box spell anything when no value is selected?

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#298]
![image](https://user-images.githubusercontent.com/14195560/53128646-366c4d80-351a-11e9-9d13-934882e1e75f.png)

**Comment by michaltrzesimiech** [comment]
Other boxes do 
![image](https://user-images.githubusercontent.com/14195560/53128753-674c8280-351a-11e9-88b6-473b4ab5fefb.png)

**Comment by Richenda** [comment]
Rather than fixing this I prefer us to make a  better settings interface down the line ;) 

Once groups and projects are functional there will be something to go there.

**Comment by Richenda** [comment]
Oh right! Yeh that should be made consistent, sorry.

**Comment by sebgrebe** [comment]
@richenda what do you want us to do? I'm not quite sure

**Comment by Richenda** [comment]
@sebgrebe you need to finish the groups functions before the proper release so that people can show group affiliation here. And this area must say N/A if the user gave no info.

**Comment by sebgrebe** [comment]
I see. Thanks! 
@taymonbeal Are you working on the groups functions for the backend?

**Comment by taymonbeal** [comment]
Haven't started work on that yet.

**Comment by Richenda** [comment]
This is by far the biggest priority
