### ISSUE TITLE
Add "organisational affiliation" to profiles

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#303]

**Comment by taymonbeal** [comment]
With the list of orgs maintained purely by staff, or do we want regular users to be able to somehow create orgs at this stage?

**Comment by michaltrzesimiech** [comment]
I learned from @Richenda we are going to use a dropdown containing a list of options we define. We will make this functionality more nuanced in later stages.

**Comment by taymonbeal** [comment]
Okay, that's easy enough. Two other questions:
- Are the options for each group just "affiliated" or "not affiliated", or is there anything else associated information that we want to have?
- Is this entirely self-reported by users?

**Comment by sebgrebe** [comment]
I can't do this without this field being added to the model, right? (I see I've been assigned to this) And can we do this given that we already have some profiles in the db or would they have to be removed again?

**Comment by taymonbeal** [comment]
Yes, the field needs to be added to the model. Yes, we can make this kind of change without wiping the database, though we have to be more careful about it than before the launch.

**Comment by sebgrebe** [comment]
Do you want to add it to the model then (if it's delicate) or should I go ahead with this?

**Comment by taymonbeal** [comment]
We need answers to the above questions from @michaltrzesimiech.

**Comment by Richenda** [comment]
@sebgrebe go ahead. Not delicate

**Comment by sebgrebe** [comment]
@Richenda Taymon says up thread that we need answers to these questions:

> * Are the options for each group just "affiliated" or "not affiliated", or is there anything else associated information that we want to have?
* Is this entirely self-reported by users?

Can you give us these answers?

**Comment by Richenda** [comment]
@taymonbeal yes self reported by users. Yes affiliated or not affiliated. I did explain this the first time. Remember this is a no frills temporary thing that we will only run until we have the EA Projects feature ready

**Comment by sebgrebe** [comment]
I'll go ahead and add this

**Comment by Richenda** [comment]
I was busy answering that

**Comment by sebgrebe** [comment]
> I was busy answering that
Ah :)

**Comment by taymonbeal** [comment]
I wanted to know because certain potential ways of doing this make certain other things harder later. But it sounds like the entire feature is eventually going to be replaced with something else, so we needn't worry (and I forgot that particular detail, sorry).

**Comment by Richenda** [comment]
I shall find it in my heart to forgive you ;)

**Comment by sebgrebe** [comment]
with this list: https://docs.google.com/spreadsheets/d/1At_tJTNhYticH_HLqoEv-yJv3wV260mLQ4g44ngGOV0/edit?usp=sharing
