### ISSUE TITLE
Add the ability for users to become organisers; organisers to edit or delete groups

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#304]
As a regular user that is not a member of group A
When I enter group A's profile
I can add myself to that group

As a regular user that is already a member of group A
When I enter group A's profile
I can remove myself from that group

As a regular user that is already a member of group A
When I enter group A's profile
I can claim a group as it's organiser

As a group A's organiser,
When I enter group A's profile
I can edit any detail of that group

As a group A's organiser,
When I enter group A's profile
I can delete that group

As any user
When I enter my profile
It lists the groups I belong to
And it lists the groups I organise separately

Users can be members or organisers of many groups (1:\*)
A group can have many organisers (1:\*)
Each group should display a full list of its members.
Each group should display a full list of its organisers separately

**Comment by taymonbeal** [comment]
Wait, surely you don't want just anyone to be able to become an organizer of any group without approval from anyone else, do you?

**Comment by michaltrzesimiech** [comment]
Sure! I wanted to not forget to specify that, actually. lean@eahub.org should get a notification with a link to approve a claim. The message should contain a link to the profile of the applicant and ideally their email address.

**Comment by michaltrzesimiech** [comment]
It could also be handled through the admin panel, whatever option is easier to implement at this stage.

**Comment by michaltrzesimiech** [comment]
Both ways are the ideal future state.

**Comment by taymonbeal** [comment]
Do all changes to organizer status have to go through LEAN, or can existing organizers also add and remove organizers for their own groups?

**Comment by michaltrzesimiech** [comment]
> Do all changes to organizer status have to go through LEAN, or can existing organizers also add and remove organizers for their own groups?

Existing organizers should be able to add and remove organizers, but LEAN should ideally be notified by email or a notification in the admin panel (or both). We can deprioritise this for a later stage if meeting this requirement doesn't come at a trivial cost.

**Comment by michaltrzesimiech** [comment]
The issue is partially covered by: https://github.com/rtcharity/hubreboot/issues/149

**Comment by michaltrzesimiech** [comment]
The issue is partially covered by: https://github.com/rtcharity/hubreboot/issues/83

**Comment by taymonbeal** [comment]
Who should be able to create groups?

**Comment by michaltrzesimiech** [comment]
> Who should be able to create groups?

Any user. lean@eahub.org should ideally get a notification on that.

**Comment by michaltrzesimiech** [comment]
Added the requirement: 

> Each group should display a full list of its members.
> Each group should display a full list of its organisers separately

As this turned slowly into epic, do let me know if you'd prefer me to break this down into several issues.

**Comment by taymonbeal** [comment]
I think this is three different overarching issues:
- Membership in groups
- Organizer status in groups
- Requesting organizer changes from LEAN

**Comment by taymonbeal** [comment]
Also, do you want any kind of revision history or audit trail or anything?

**Comment by michaltrzesimiech** [comment]
> Also, do you want any kind of revision history or audit trail or anything?

We don't have to include this into the scope at this stage unless it's trivial to implement.

**Comment by taymonbeal** [comment]
It's not trivial. Of course, if we launch user editing without it then any edits that are overwritten before we implement it will be lost forever, but I'm okay with that if you are.

**Comment by michaltrzesimiech** [comment]
I'm ok with this.

**Comment by michaltrzesimiech** [comment]
This is currently our top priority

**Comment by taymonbeal** [comment]
I'm beginning work on this now.

One quick question: Are we later likely to want to add any additional data to a user's organizer status, or is it purely binary?

(Some context, since I keep asking things like this: When setting up a relationship between two different models, like users and groups, there are two ways to do it. One's more convenient, the other allows data to be later attached to the relationship. Switching after the fact is a pain.)

My current guess is yes, we'll want to add metadata later. In particular, I imagine it might be desirable to give people organizer permissions without having them be listed publicly. (Though of course we don't need this now.)

**Comment by michaltrzesimiech** [comment]
> Are we later likely to want to add any additional data to a user's organizer status, or is it purely binary?

That's a good question. We will want to add metadata later (like milestoning times at which a person was an organiser, probably different levels of privilege, maybe more).

**Comment by taymonbeal** [comment]
If you want to track history, we have to add some level of support for that now, or else it won't remember anything from before that support was added.

**Comment by michaltrzesimiech** [comment]
We don't really care about history to be complete. Adding it at some point later is enough for our use case.
