### ISSUE TITLE
Add the "Other" free text field under "Expertise", "Cause areas", "Topics" to "Available as a speaker"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#306]

**Comment by taymonbeal** [comment]
Sorry, confused what you mean. Those things don't currently have "other" free text fields, because we decided we wanted to implement an option for users to suggest new options when we get the chance, and we didn't want to migrate from a free-text field onto that.

**Comment by sebgrebe** [comment]
@michaltrzesimiech any update on this after @taymonbeal's input?

**Comment by michaltrzesimiech** [comment]
@Richenda and I decided that the "Other" field will add substantial value, so we would like to work on these on priority.

Not sure what you mean by 

> we didn't want to migrate from a free-text field onto that.

**Comment by sebgrebe** [comment]
> Not sure what you mean by

@taymonbeal suggested to remove the "other" category so that we don't have lots of user generated categories, which in some cases might just be different because of spelling (e.g., "Education", "education", "educational sector"). If we were to provide the categories instead, it's easier to do data analysis from this.

But I believe you're saying it's more important for you that users have the ability to add a category if they don't fit into the existing ones? If so, I'm happy to get going with this.

**Comment by taymonbeal** [comment]
The thing we actually wanted was for people to be able to add categories but then for those to become part of the list, presumably after moderation or deduplication. That might take longer though.

**Comment by michaltrzesimiech** [comment]
> The thing we actually wanted was for people to be able to add categories but then for those to become part of the list, presumably after moderation or deduplication. That might take longer though.

This sounds good. It also sounds like we can first let users add free text and then add more complexity (i.e. manual classification, i.e. in a form of suggestions based on keywords)?

**Comment by michaltrzesimiech** [comment]
Highlighting for @Richenda

**Comment by taymonbeal** [comment]
There'll be an annoying manual transition, but it's possible. One product question is whether users will enter a bunch of special-snowflake causes and then expect it to continue working that way. Perhaps the goal should be to have both a free-text explain-your-prioritization-with-all-the-nuances field and a more structured field suitable for statistical analysis?

**Comment by michaltrzesimiech** [comment]
Definitely a q for @Richenda

**Comment by Richenda** [comment]
>There'll be an annoying manual transition, but it's possible. One product question is whether users will enter a bunch of special-snowflake causes and then expect it to continue working that way. Perhaps the goal should be to have both a free-text explain-your-prioritization-with-all-the-nuances field and a more structured field suitable for statistical analysis?

Since we already give people a bio area they should probably use that for the nuance. Is it possible to have automated lists that allow somebody to write a new suggestion but don't add it to the list if it is very similar to something that's already there? For example if we have Software Engineer, and someone writes 'software engineer', it should know not to add two with different capitalisation. Another way it can work is that each time a user adds a category to the list, it goes into a queue that an admin has to visually review and 'accept' before it goes live?

**Comment by michaltrzesimiech** [comment]
Ok, so the main purpose of the field "Other" for "Cause areas" is to include niche interests that shouldn't be similar to any particular value in that set. We want to report it out as "Other" and be able to manually look into what data it contains. If we end up having a lot of similar datapoints under "Other", we should add that as a value to that set.

The reason we want "Other" for "Expertise" is because it'll be hard to include enough of possible fields. Again, we can run a manual analysis after a while and decide to add more values to that set and reconcile that data with a script or manually. 
I'll move the discussion on how we want to modify the content to this place: https://github.com/rtcharity/eahub.org/issues/368

The reason we want "Other" for "Topics [a person can speak about]" is exactly because that's sometimes hard to classify and a free text is more informative than a predefined category, though something of a tag cloud could be an interesting addition.

**Comment by michaltrzesimiech** [comment]
So to simplify, we want just a free text field for "Cause areas" and "Expertise". We can use that same thing for "Topics", though it would be ideal to add a tag cloud or something similar to aid navigation/reporting.

**Comment by michaltrzesimiech** [comment]
Moved the tag cloud idea to this place: https://github.com/rtcharity/eahub.org/issues/369

**Comment by sebgrebe** [comment]
> So to simplify, we want just a free text field for "Cause areas" and "Expertise". We can use that same thing for "Topics", though it would be ideal to add a tag cloud or something similar to aid navigation/reporting.

Just to make sure I implement this correctly: So "Topics" is just the union of the cause areas and expertise lists?

**Comment by taymonbeal** [comment]
I would be in favor of doing only a freeform text field for "topics I speak about" for now, with no multiple-choice option.

**Comment by sebgrebe** [comment]
> I would be in favor of doing only a freeform text field for "what I speak about" for now, with no multiple-choice option.

Will implement this.
