### ISSUE TITLE
Add ability to report a group as inactive

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#308]
As any user
When I enter any group's profile
I can report that group as inactive
By clicking a button "Report as inactive" that either

1. sends this standardised message to lean@eahub.org:

> Group <name> was reported as inactive by <user>

2. Or displays that information in the admin panel

When group is marked as inactive (active=false), display on map as grey.

**Comment by michaltrzesimiech** [comment]
Please deprioritise to "fix soon after launch" if the cost of this is >2 hours.

**Comment by taymonbeal** [comment]
Only LEAN can change the activity status of a group?

**Comment by taymonbeal** [comment]
Blocked by #278.

**Comment by michaltrzesimiech** [comment]
This is currently among our highest priorities

**Comment by sebgrebe** [comment]
> Blocked by #278.

There is a PR for #278, once this is merged, I'm happy to start working on this ticket

**Comment by sebgrebe** [comment]
> Blocked by #278.

There is now a PR for #278. Once this has been approved, I am happy to work on this issue.

**Comment by taymonbeal** [comment]
You can start working on this now if you like. They're not technically related, we just don't want to deploy them out of order.
