### ISSUE TITLE
Broken-link reporting emails don't show end-user IPs

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#321]

**Comment by taymonbeal** [comment]
We still need to get these emails working again, or at least try to.

**Comment by taymonbeal** [comment]
Still getting lots of spam. First step is to find out where it's coming from.

**Comment by taymonbeal** [comment]
We're now getting broken-link emails consistently, as well as having actual 404 metrics. There remains _lots_ of room for improvement, but there's no technical reason why those improvements can't be made post-launch.

@michaltrzesimiech, are you satisfied with the state of our broken-link monitoring? Is there anything else you'd like me to try to get in pre-launch?

**Comment by michaltrzesimiech** [comment]
No, we should be good to look into this post-launch.

**Comment by taymonbeal** [comment]
Closing this in favor of improved handling of individual paths.
