### ISSUE TITLE
Import inactive groups from the Airtable

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#333]

**Comment by taymonbeal** [comment]
Will we need to do this on an ongoing basis going forward?

**Comment by michaltrzesimiech** [comment]
The priority is to import the latest changes, which there are many. If the integration was possible at a similar cost (i.e. +/- 3 story points), I'd say let's go the extra mile.

**Comment by taymonbeal** [comment]
Is the intention that the Airtable will remain the source of truth for this data going forward?

**Comment by michaltrzesimiech** [comment]
No, the intention is to use the Hub as a single source of truth, on the premise that it's going to be equally as user-friendly. I think the only use case where Airtable is currently more user-friendly is where we have a lot of manual changes to make in multiple groups. 
But I'd imagine that for such a scenario it would be easier to upload a csv export, rather than building an integration with the Airtable API?

**Comment by taymonbeal** [comment]
If this is going to be the last time we sync from Airtable, and then from now on the Hub is the source of truth, then that code's already written and all I have to do is run it. On the other hand, if you want to keep importing data from the Airtable again in the future, then we need a story about, e.g., what happens if the same row has been edited in both the Hub and the Airtable.

**Comment by michaltrzesimiech** [comment]
I just confirmed with CEA that they might want to update the table on Friday. They're trying to identify which of the groups are inactive. I suppose we might work together to do this using the Hub rather than the Airtable. The operation should be limited to either deleting the groups or switching the "active" flag if we are going to implement that by then (https://github.com/rtcharity/eahub.org/issues/308)

**Comment by michaltrzesimiech** [comment]
I'd say we should definitely run the script now and assume it's either the last time we do this, or that the Friday run will be the last.

**Comment by taymonbeal** [comment]
The existing migration only imports groups that were marked as Active on the Airtable. Do we want to have inactive groups in our database too?

**Comment by taymonbeal** [comment]
And yeah, that works, so long as nobody makes any changes to the groups in the admin panel before Friday, unless they're okay with those changes getting deleted then.

**Comment by michaltrzesimiech** [comment]
> The existing migration only imports groups that were marked as Active on the Airtable. Do we want to have inactive groups in our database too?

We do not want inactive groups in our database before we have #308.

> And yeah, that works, so long as nobody makes any changes to the groups in the admin panel before Friday, unless they're okay with those changes getting deleted then.

You're right. I'll make sure we don't use the admin panel by Friday.

**Comment by taymonbeal** [comment]
Will we want them after we have #308? If so, we should prioritize getting #308 done by Friday, and then include those groups in Friday's Airtable import. (The code to do that doesn't exist yet but can be added.)

**Comment by michaltrzesimiech** [comment]
The main issue is that the `*@effectivealtruismhub.com` emails no longer work, so what we silently launched with has a fair chance of misleading some of people that visit the Hub prior to the official announcement. I'll add the label Production Emergency.

> Will we want them after we have #308?

Yes. But we can also run that update later than on Friday. Friday is the date for getting an updated airtable from CEA.

**Comment by michaltrzesimiech** [comment]
I'd say we should expect to learn about a few groups being inactive, and we could run those changes manually. Whereas what we currently have in the Airtable is critically different to what we currently have in production.

**Comment by taymonbeal** [comment]
Rerunning migration now.

**Comment by taymonbeal** [comment]
I think I broke things. Trying to fix...

**Comment by taymonbeal** [comment]
Hub's back up now but with an empty groups map. Rerunning migration now, hopefully avoiding the problem from last time.

(Which, for the record, was that the unmigrate command that I ran on my local machine kept going and bringing down the database after it was done. Continuous deployment would have prevented this.)

**Comment by taymonbeal** [comment]
Okay, fire's out. @michaltrzesimiech, please verify that this looks like it's supposed to.

**Comment by michaltrzesimiech** [comment]
A short random data quality check showed that we should be good. Thanks!

**Comment by taymonbeal** [comment]
Wait, I thought we still needed to do this again on Friday.
