### ISSUE TITLE
Do we still want to use project boards?

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#336]
Would like to figure out what their role in our process is going forward.

**Comment by Manoj-nathwani** [comment]
I personally switch over to just using github issues filtered by labels or milestones as we were going through cards so quickly 😅 it wasn't worth keeping them pretty on a project board haha

**Comment by taymonbeal** [comment]
I can work through the slush pile easily enough; what I especially want to know is whether they're needed/useful for the product or project managers.

**Comment by michaltrzesimiech** [comment]
> whether they're needed/useful for the product or project managers.

Not really. I kept them in case they're useful to you, the developers.

**Comment by taymonbeal** [comment]
I suppose we should get rid of them for now, then, and maybe bring them back later if they turn out to be useful for something.

**Comment by michaltrzesimiech** [comment]
https://rtcharity.slack.com/archives/GBUD95PT8/p1551117955204100
