### ISSUE TITLE
Authenticated profile data

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#337]
This isn't an immediate priority, but I've already started thinking a little about how it would work technically, so I'd be interested to know whether there's interest.

For things that users enter, like organizational affiliation or website or Twitter account or what have you, would there be any interest in programmatically verifying that it's actually their Twitter account? Either mandatory, or adding a "Verified" badge if they do it?

**Comment by michaltrzesimiech** [comment]
It's definitely not on top of our priorities list rn, but sure, that would be nice. I guess there's nothing holding us from applying this retroactively, right?

**Comment by victor-yunenko** [comment]
I'll move it out to the feedback tool for now - https://feedback.eahub.org/posts/26/add-the-ability-to-verify-organizations-websites-twitter-membership-ownership
