### ISSUE TITLE
Periodic check-ins?

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#338]
I'm of two minds as to whether we should restart doing periodic check-ins of what people are working on. On the one hand, it's useful for me to know what everyone else is doing so that I can factor that into what I'm doing, e.g., avoid duplicating work. And I'm sure the product and project managers would like to know this too. On the other hand they mean committing to deadlines for short-term tasks much more frequently (since people are counting on you doing what you said you'd do), which I'm a bit reluctant to do since I'm doing all of this in what spare time I can manage. And I don't want to wind up flaking again. What do other people think?

**Comment by michaltrzesimiech** [comment]
This question is coming back periodically and I think that being of two minds about calls is the default mode for us. Would it be better if I set up a daily/weekly recurring thread on Slack where everyone could define their objectives for a given day/week? This would save us from having to dial in at a fixed day and hour.

**Comment by taymonbeal** [comment]
I'd be okay with trying this.

**Comment by michaltrzesimiech** [comment]
Ok, we're all set up

**Comment by michaltrzesimiech** [comment]
We decided to take a different approach after all https://rtcharity.slack.com/archives/GBUD95PT8/p1551117955204100
