### ISSUE TITLE
Move non-hub sites away from eahub.org

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#341]
• We currently let groups have subdomains like saar.eahub.org.
• For security reasons, we have to move everything that is not the Hub away from the domain eahub.org. This entails registering a separate domain, say eagroups.org.

**Comment by michaltrzesimiech** [comment]
We need a domain first. https://rtcharity.slack.com/archives/GC1BSH8AH/p1551102035004400

**Comment by taymonbeal** [comment]
That link isn't working for me.

**Comment by michaltrzesimiech** [comment]
Try https://rtcharity.slack.com/archives/GBUD95PT8/p1551373958001000

**Comment by michaltrzesimiech** [comment]
Bought eahub.group. We're ready to move on.

**Comment by michaltrzesimiech** [comment]
@jpzg will you be around to help with this? tl;dr: We need to move all websites like location.eahub.org under eahub.group.

**Comment by michaltrzesimiech** [comment]
Closing as happening elsewhere
