### ISSUE TITLE
Synchronize resources.eahub.org content

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#342]
Putting this here rather than in https://github.com/rtcharity/resources.eahub.org because this might involve technical integration with the main EA Hub app.

I'm told that CEA expressed some concern about this content getting out of date. I'm curious what we might do about that. Do we want the resources repo to be the source of truth for the content in it? Or would it be better to pull and display that content from other sources?

Not an immediate priority.

**Comment by Richenda** [comment]
This is @Michal he has the strategy

**Comment by michaltrzesimiech** [comment]
CC: @marcinkowrygo

**Comment by michaltrzesimiech** [comment]
My opinion is it would be ideal if we mirrored the source content elsewhere, also because it would spread the cost of maintaining it to authors and maintainers other than ourselves. I'd say it would be ideal if we made snapshots of content periodically so that we don't end up with broken links.

**Comment by taymonbeal** [comment]
This is a big project and will not realistically launch even in Plato unless we deprioritize a bunch of other stuff, which it sounds like we don't want to do.

That said, if/when we do this, the first things we need to figure out is what sources we want to be mirroring content from. Got a list or anything?

**Comment by michaltrzesimiech** [comment]
Closing as resolved in https://github.com/rtcharity/resources.eahub.org
