### ISSUE TITLE
Let people change their email address

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#343]

**Comment by sebgrebe** [comment]
blocked by https://github.com/rtcharity/eahub.org/pull/346

**Comment by sebgrebe** [comment]
Looked into this and it seems this involves some somewhat complicated backend work as the email is not a simple field of the profile model, but part of the user field (user.email). I did a bit of research, but couldn't quickly figure out how to expose the email to the frontend in forms.py.

Someone with more django knowledge is probably better suited to do this.

**Comment by taymonbeal** [comment]
This isn't that hard, I can take care of it.
