### ISSUE TITLE
Let people have an account without having a profile

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#344]
We may want more sophisticated privacy options than this later, but this feels like the bare minimum.

Do the product people have any particular thoughts on this?

**Comment by michaltrzesimiech** [comment]
We definitely don't need this for the publicised launch, so I'll remove the milestone. @Richenda may have an opinion on how we want to tackle this.

**Comment by patbl** [comment]
Besides having a profile, what can you do with an account that you can't do without one? Donation swapping?

If people wanted and account and anonymity, they could use a pseudonym.

My guess is that few people would use this.

**Comment by victor-yunenko** [comment]
I'll move it out to the feedback collector for now - https://feedback.eahub.org/posts/27/let-people-have-an-account-without-having-a-profile
