### ISSUE TITLE
Design a UI for clearing profile picture

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#347]
As @sebgrebe observed in #346, Django's built-in way of handling this is ugly.

I can build this in Django if somebody else figures out what it should look like.

**Comment by michaltrzesimiech** [comment]
Unless @Richenda has any preferences here, I'd say let's go with whatever is simple and not blatantly ugly. A simple hypertext under "Image" in profile/edit/ that works if (image_present=true) would be good to begin with for me

![image](https://user-images.githubusercontent.com/14195560/54364430-21bb3b00-462a-11e9-8309-c797a14af208.png)

Moving into the scope of Publicised Launch in case @sebgrebe has bandwidth for this. Otherwise, let's push it back to Plato.

**Comment by taymonbeal** [comment]
Wait, I'm confused about how this solves the problem. What do you mean by "hypertext"?

**Comment by michaltrzesimiech** [comment]
Sorry, I meant a simple link saying "Remove current picture" (and doing exactly that).

**Comment by taymonbeal** [comment]
Do you want that to be separate from the form, such that if a user clicks it it then discards their progress in the form? That's what a link generally does.

**Comment by taymonbeal** [comment]
Also, for security reasons this can't be a pure link, it has to be either a form button or some kind of JavaScript thing.

**Comment by taymonbeal** [comment]
I think I would be in favor of Django's built-in thing but with a new template (possibly with some JavaScript) to make it look nicer.

**Comment by sebgrebe** [comment]
> I think I would be in favor of Django's built-in thing but with a new template (possibly with some JavaScript) to make it look nicer.

OK, if you could implement the Django part (or direct towards some documentation and I do it), then I can take care of making it look prettier with CSS/JS

**Comment by taymonbeal** [comment]
This reopens the original question: What exactly do we want this to look like? Assume that it's part of the form and doesn't take effect until the user submits.

**Comment by sebgrebe** [comment]
As you say this can't be a link, I suggest going with a button. I think this fits Michael's spec 
> whatever is simple and not blatantly ugly

**Comment by taymonbeal** [comment]
How would the button work, given the constraint (assuming we want this to work the same way as Django's built-in thing) that it can't take effect until the user submits the form? Is the idea that when the user clicks the button it clears what's already in the selector?

**Comment by sebgrebe** [comment]
> Is the idea that when the user clicks the button it clears what's already in the selector?

Sounds good

**Comment by taymonbeal** [comment]
Okay, cool. Can you implement this? It shouldn't require any backend changes. What you'll need to do is add an additional `<input>`, with `name="image-clear"` and `value="on"`, that's provided if and only if the user has elected to delete their profile image without providing a replacement. If you do that, Django will take care of the rest.

**Comment by sebgrebe** [comment]
on it

**Comment by sebgrebe** [comment]
> What you'll need to do is add an additional <input>, with name="image-clear" and value="on", that's provided if and only if the user has elected to delete their profile image without providing a replacement. If you do that, Django will take care of the rest.

One question, to make sure I understand this right: The input iff the user chooses to delete their profile image? So they have to first click "Delete picture" and then said input occurs and then they have to submit that? Why not just have that input always sitting there so that users don't have to click twice?

**Comment by taymonbeal** [comment]
The behavior we need, in order to be compatible with the current Django backend, is:
- Regardless of what the user clicks in the form, nothing changes for real until they submit it
- When the form is submitted, that input is present if they elected to clear their profile picture, and absent if they didn't

I do not have strong opinions on what specific UI is used to implement this behavior. Can you lay out the precise behavior you have in mind for the button? Or I could try to come up with a precise specification, if this would be useful.

**Comment by sebgrebe** [comment]
What I'm trying at the moment: Adding a button that removes the image as a value from our image input. This should satisfy both points you mention

**Comment by taymonbeal** [comment]
Does that add the additional `<input>`? If not, then when submitted it will not delete the user's existing profile picture.

**Comment by sebgrebe** [comment]
Ah, I see. I was assuming the empty value would override the existing profile pic on submit.
I'll add the input you mention

**Comment by taymonbeal** [comment]
Nope, the behavior is:
- If `image` is provided, but not `image-clear`, set the user's profile image to the newly uploaded one
- If `image-clear` is provided, but not `image`, delete the user's profile image
- If both `image` and `image-clear` are provided, display an error message
- If neither `image` nor `image-clear` is provided, leave the user's profile image alone

**Comment by taymonbeal** [comment]
Ideally the interface would be designed so as to make the third case impossible.

**Comment by sebgrebe** [comment]
OK, understand now. We need the button that toggles image-clear, otherwise we get situation 3 which triggers the error message.

**Comment by taymonbeal** [comment]
Note that `image-clear` can be an `<input type=hidden>`, in which case the user doesn't have to click it directly, provided that you can make the button add and remove it as appropriate.
