### ISSUE TITLE
Add "Report abuse" button to personal and group profiles

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#352]

**Comment by taymonbeal** [comment]
This is fairly trivial if you're okay with it emailing the admins and not doing anything else.

**Comment by michaltrzesimiech** [comment]
Yes, that should be enough for now!

**Comment by michaltrzesimiech** [comment]
@Richenda should have the priority to decide how this should look like

**Comment by taymonbeal** [comment]
Can we assume that it'll look like a button? I'll leave it to the frontend people to figure out the exact design of the button.

**Comment by Richenda** [comment]
Good idea. Imo it would make most sense for it to be an additional button under the profile name. Like right next to 'message'. Please don't implement until after the public launch.
<img width="556" alt="screenshot 2019-03-04 at 15 16 40" src="https://user-images.githubusercontent.com/14843012/53769387-98b93c80-3e90-11e9-9922-0489151c78e3.png">

**Comment by sebgrebe** [comment]
> Please don't implement until after the public launch.

Moved this to Plato so that I don't jump the gun on this.

**Comment by taymonbeal** [comment]
This needs to get in before the freeze. People are in fact sending us spam.

**Comment by sebgrebe** [comment]
> Good idea. Imo it would make most sense for it to be an additional button under the profile name. Like right next to 'message'. Please don't implement until after the public launch.
> <img alt="screenshot 2019-03-04 at 15 16 40" width="556" src="https://user-images.githubusercontent.com/14843012/53769387-98b93c80-3e90-11e9-9922-0489151c78e3.png">

I'm a bit sceptical whether it's a good idea to have that right under the profile and group names. It might be just me, but I find it off-putting that the word "abuse" shows up so prominently right next to my name.

![Screen Shot 2019-04-19 at 12 18 11](https://user-images.githubusercontent.com/15908208/56422067-8b6bdc00-629d-11e9-9d3f-b90447ed5771.png)

Instead, we could have it at the bottom, where it's more discrete

![Screen Shot 2019-04-19 at 12 20 00](https://user-images.githubusercontent.com/15908208/56422071-8e66cc80-629d-11e9-8f65-6081fb238de5.png)

**Comment by sebgrebe** [comment]
I could also use some input from product on the wording for this. For the moment, I've implemented the user flow as follows:
- Click "Report abuse" button
- Field appears that says: "I believe that this profile is spam"
- User clicks "Confirm"
- Admins receive email: 
> Dear Admin,
User X reported profile Y as abuse.
In case the profile is abuse, remove it and send an email to the user associated with profile Y to inform them of your decision.
Also let user X know of the outcome of your inquiry by emailing them at X@email.com.
- User sees message on page: 
> Thank you, we have received your report. Our admin team will send you an email once they have looked into it. 

Is this OK? I wonder whether we should only use the word "spam". Or is the point of this button more general, i.e., also for reporting inappropriate conduct that wouldn't qualify as spam (e.g., racist content). In this case, do we want to add some free text form where users can state what the reason for their report is?

**Comment by Richenda** [comment]
>Is this OK? I wonder whether we should only use the word "spam". Or is the point of this button more general, i.e., also for reporting inappropriate conduct that wouldn't qualify as spam (e.g., racist content). In this case, do we want to add some free text form where users can state what the reason for their report is?

I think the ideal would be giving people a list of reasons to choose from but not free text. Having been a moderator for a long time, people do kind of abuse report systems by using it to complain and vent when it's not something that admins really should be interfering on. It also adds a cost to us in providing support. So I'd pick some likely reasons - spam, fake account, offensive content is what springs to mind - and then let people pick one and put our email address there if they need to talk in more detail. The rest looks good!

**Comment by sebgrebe** [comment]
> So I'd pick some likely reasons - spam, fake account, offensive content is what springs to mind - and then let people pick one and put our email address there if they need to talk in more detail.

Good idea, I'll implement that

**Comment by sebgrebe** [comment]
One further question: At the moment, I've put the name and email of who is reporting abuse in the email the admins receive. Should we allow people to report abuse anonymously, i.e., not mention in the email who has sent the report? 

This seems to be the better way of doing it as some people might be more comfortable with reporting someone's profile as offensive when they can do so anonymously.

**Comment by taymonbeal** [comment]
More prosaically, I don't think we want to require people to create accounts.

**Comment by sebgrebe** [comment]
> More prosaically, I don't think we want to require people to create accounts.

Maybe a bit of your message got cut: are you arguing for people being able to report without being logged in? I was wondering whether this could create an issue of bots randomly clicking the report button

**Comment by taymonbeal** [comment]
Not sure if that would happen. We can IP block malicious bots maybe? Dunno what the tradeoff looks like here.
