### ISSUE TITLE
Modify the content of "Expertise"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#368]
We should make sure that we don't discriminate any of the fields we already know are popular based on this analysis: 
https://forum.effectivealtruism.org/posts/S2Sonawxz2cY4YdXK/ea-survey-2018-series-community-demographics-and

I propose that we add those values to "Expertise":
Philosophy, 
Humanities, 
Psychology,
Physics,
Medicine,
Other Science

**Comment by taymonbeal** [comment]
Can you remind me what the intended use case for this field is?
