### ISSUE TITLE
Add a tag cloud to "Topics" [a person can speak about]

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#369]
Re https://github.com/rtcharity/eahub.org/issues/306#issuecomment-469718302

**Comment by michaltrzesimiech** [comment]
Is there anything better than a tag cloud to help us navigate around the areas people could speak about? Should we do this now or later, once we have more data?

**Comment by Richenda** [comment]
I think the ideal in this case would be a category that we provide (after more data) and then a custom field being more specific.

**Comment by taymonbeal** [comment]
Personally, I'm not convinced that this is usefully categorizable; the variety may simply be too wide. In any event, AFAIK the only intended use case for this is to help people find speakers (as opposed to, e.g., statistical analysis), so we may simply want to let people narrow down the list based on more easily categorizable fields that are good proxies for this (cause areas, skills, and org affiliations), and then from there just read the freeform descriptions of what people speak about.
