### ISSUE TITLE
Membership form control doesn't have pretty Bootstrap multiselect

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#372]

**Comment by sebgrebe** [comment]
do you mean this? Box is too wide?
![Screen Shot 2019-03-13 at 20 27 53](https://user-images.githubusercontent.com/15908208/54312312-88127000-45ce-11e9-99ae-18f17b1ac66b.png)

**Comment by taymonbeal** [comment]
Huh, when I filed this there was only a browser-standard multiselect without checkboxes. It looks like this somehow got fixed along the way. (You're right that it's too wide though, and a PR to fix that is welcome.)
