### ISSUE TITLE
For "Organisers", sort list alphabetically and add a search box

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#377]
For "Organisers" in group/*/edit, sort the list alphabetically, preferably by last name. Add a search box, or at least make it responsive to stroking letters on keyboard.

![image](https://user-images.githubusercontent.com/14195560/53902757-c4eecd80-3ff6-11e9-8722-753ae5064dc1.png)

**Comment by Richenda** [comment]
Yeh keyboard input ordering would be ideal.

**Comment by taymonbeal** [comment]
Fixed in #397.
