### ISSUE TITLE
Change text in //*[@id="claim_group"]/p

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#378]
In this example, we do know who organises this group. Someone else might still want to claim this group, so let's remove the "We dont know..." part by changing the text to:

"Our admins will look into your request to claim this group and contact you shortly."

![image](https://user-images.githubusercontent.com/14195560/53903009-64ac5b80-3ff7-11e9-8645-899d0cbc62d7.png)

**Comment by taymonbeal** [comment]
I thought the intention was that the claim button wouldn't appear at all unless the group had no known organisers.

**Comment by michaltrzesimiech** [comment]
That would makes sense as well, once we have report as inactive. Not sure myself, but @Richenda might have a clear preference.

**Comment by sebgrebe** [comment]
Let me know whether you prefer
1) Keeping button when organisers exist, but removing "We don't know..."
2) Removing button when organisers exist

Currently working on something related and could quickly implement it

**Comment by michaltrzesimiech** [comment]
I think it would make sense to display the claim button always, as there are several scenarios where this could be used when another user is already an organiser, i.e. when that user is not responsive, but group itself is being active.

**Comment by sebgrebe** [comment]
Just implemented the opposite :D But np, will change back

**Comment by michaltrzesimiech** [comment]
Aw, crap, sorry. I was too slow.

**Comment by sebgrebe** [comment]
> Aw, crap, sorry. I was too slow.

Nah, I jumped the gun ;)

**Comment by Richenda** [comment]
> I think it would make sense to display the claim button always, as there are several scenarios where this could be used when another user is already an organiser, i.e. when that user is not responsive, but group itself is being active.

Yup, this ^ Sorry for slow response
