### ISSUE TITLE
For "EA Groups" in profile/edit/community, sort list alphabetically and add a search box 

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#382]
profile/edit/community
![image](https://user-images.githubusercontent.com/14195560/53915700-49e8df80-4015-11e9-8268-ae39c424cf7f.png)

**Comment by Richenda** [comment]
Good call

**Comment by taymonbeal** [comment]
Fixed in #397, except for the search box which was factored out into #403.
