### ISSUE TITLE
Add "Other" to "Group Type"

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#390]
![image](https://user-images.githubusercontent.com/14195560/53985403-58e09800-40d0-11e9-99a1-1f36b26c7c86.png)

We have at least 1 corporate group and discuss regional groups. This can get useful and asked for quickly.

**Comment by Richenda** [comment]
Apologies to Taymon. He asked if I thought there would be more types of group and I said no.

**Comment by taymonbeal** [comment]
We kind of already have this, in that some groups have no type. I suppose we could change the UI to say "Other" if that would be useful.

When we finally overhaul geocoding we might want to have group types correspond to what kind of location the group gets.

**Comment by michaltrzesimiech** [comment]
There are regional and national and corporate groups on our list, so adding "other" was the simplest thing I could come up with. We could add "regional", "national" and "corporate" instead or in addition to "other". We could also wait for the new geocoding. What currently makes sense to me is to add "other" (because a "nation-wide" group is definitely not a "–", but we don't have this clearly defined/streamlined yet).

**Comment by taymonbeal** [comment]
That sounds like it can be done as a UI change without touching the database schema, so it seems reasonable to do it that way for now.
