### ISSUE TITLE
Add other field on lists which toggles other text field

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#405]
suggested [here](https://github.com/rtcharity/eahub.org/pull/402#pullrequestreview-214029421)

**Comment by victor-yunenko** [comment]
We've talked today about the possibility of adding a multi-step form in the future (probably on vuejs) and a ckeditor WYSIWYG field for the text description. I guess we could specify it in more detail at that stage? I'll close this ticket for now then, please feel free to reopen if needed.
