### ISSUE TITLE
Customise who gets group claim emails

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#411]
These are currently going to admins, but @Richenda should also get them. Devs (@taymonbeal , @sebgrebe) actually don't need to get them.

**Comment by sebgrebe** [comment]
do we need to create new role for this? Alternatively, quick and dirty solution would be to hardcode an email address in (e.g., eahub@lean.org)

**Comment by taymonbeal** [comment]
Either of those is an option, although the email address should be specified in a setting rather than hardcoded. I think I'd say do that for now and then we can add the role thing later.
