### ISSUE TITLE
Two-factor authentication

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#415]
The primary reason to support this is to prevent privileged users, i.e., us, from getting phished, since we have access to a bunch of sensitive user data. As an added bonus, this would also allow regular users to secure their accounts better if they're paranoid enough to want to.

**Comment by patbl** [comment]
FWIW, I work for a website with over 100 million registered users, and it doesn't have 2FA. It hasn't been a problem.
