### ISSUE TITLE
Continuously scan for outdated, insecure, or noncompliant dependencies

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#418]
requires.io or pyup might be useful for this.

**Comment by michaltrzesimiech** [comment]
This should be covered by https://github.com/rtcharity/eahub.org/issues/666

**Comment by taymonbeal** [comment]
How does SonarCloud do this? Do they have a database of vulnerable packages that they run against our requirements.txt? Can they automatically file PRs against us to upgrade our packages?

**Comment by michaltrzesimiech** [comment]
According to: https://sonarcloud.io/documentation/user-guide/security-reports/

> Security Reports quickly give you the big picture on your application's security, with breakdowns of just where you stand in regard to each of the OWASP Top 10, and SANS Top 25 categories, and CWE-specific details.

> The Security Reports are fed by the analyzers, which rely on the rules activated in your quality profiles to raise security issues. If there are no rules corresponding to a given OWASP category activated in your Quality Profile, you will get no issues linked to that specific category and the rating displayed will be A. That won't mean you are safe for that category, but that you need to activate more rules (assuming some exist).

https://sonarcloud.io/documentation/user-guide/issues/

> While running an analysis, SonarCloud raises an issue every time a piece of code breaks a coding rule. The set of coding rules is defined through the associated quality profile for each language in the project.
> Bug – A coding error that will break your code and needs to be fixed immediately.
> Vulnerability – A point in your code that's open to attack.
> Codesmell – A maintainability issue that makes your code confusing and difficult to maintain. 

This is what our (early) attempt to scan the Hub produced before: https://sonarcloud.io/dashboard?id=rtcharity_hubreboot

**Comment by taymonbeal** [comment]
Yeah, as far as I can tell this doesn't actually check our dependencies.

**Comment by michaltrzesimiech** [comment]
That's true. GitHub is supposed to be doing this (https://help.github.com/en/articles/about-security-alerts-for-vulnerable-dependencies), but I guess we want a one stop shop for all of these

**Comment by taymonbeal** [comment]
GitHub warns us about dependencies that have had CVEs assigned. What we really want is something that 1) will warn us about _any_ dependency that becomes outdated whether it has a CVE or not, and 2) will automatically file a PR to fix it, so all we have to do is click the button.

**Comment by taymonbeal** [comment]
Oh, and while we're at it it should check for license compliance too. Though that can just happen in CI, maybe, and so doesn't need to be the same service.
