### ISSUE TITLE
Figure out how to incorporate password reset links into launch email

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#421]

**Comment by taymonbeal** [comment]
Michal, let me know when you have a template that a password reset link could go into.

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech, See https://github.com/rtcharity/eahub.org/pull/450#issuecomment-474202263

**Comment by michaltrzesimiech** [comment]
The template itself is now in our MailChimp. I'll work on the text later today.

**Comment by taymonbeal** [comment]
I don't have access to this, can you share?

**Comment by michaltrzesimiech** [comment]
Sorry, I was meaning to do that before but got distracted. Sent you an invite to join as a user.

**Comment by taymonbeal** [comment]
We're going to use a Django management command for this. Still need to figure out how to handle the email addresses that aren't in the legacy database.

**Comment by michaltrzesimiech** [comment]
There will only be emails that are in either prod or the legacy database

**Comment by taymonbeal** [comment]
Folding this into #514.
