### ISSUE TITLE
Import cause areas from legacy profiles

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#426]
Assuming we want to do this, we need to figure out how to map the legacy causes onto the new ones. The legacy ones are:

- Animal welfare
- Climate change
- Earn-to-give
- Effective giving
- Entrepreneurship
- Existential risk and far future causes
- Global poverty
- Machine intelligence risk
- Molecular nanotechnology
- Movement-building
- Nuclear technology
- Prioritization research
- Rationality
- Synthetic biology risk

There are also various freeform ones.

**Comment by Richenda** [comment]
Subsume old categories into the ones we have now like this:

**Global Poverty:** Global Poverty
**Animal Welfare/Rights:** Animal Welfare
**Long-term Future:** Climate Change, Existential Risk and Far Future Causes, Machine Intelligence Risk, Molecular Nanotechnology, Nuclear Technology, Synthetic Biology Risk
**Cause Prioritisation:** Effective Giving, Prioritisation Research
**Meta:** Movement Building, Rationality
**Remove/don't import:** Earn to Give, Entrepreneurship

**Comment by taymonbeal** [comment]
I'll assume that we want to keep the freeform ones and put them in the "Other" field.

**Comment by taymonbeal** [comment]
Have implemented this, but #479 needs to be merged first.
