### ISSUE TITLE
Import expertise areas from legacy profiles

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#427]
Assuming we want to do this, we need to figure out how to map the legacy skills onto the new ones. The legacy ones are:

- Coding
- Entrepreneurship
- Event planning
- Finance/Investment strategy
- Graphic design
- Journalism
- Law
- Management
- Marketing/Sales
- Mentoring
- Networking/Schmoozing
- Organizing groups/teams
- Outreach
- PR
- Persuasion
- Philanthropy
- Public policy/Politics
- Public speaking
- Recruitment
- Research/Analysis
- Statistics/Data science
- Strategy
- Video production
- Web development

There are also various freeform ones.

**Comment by michaltrzesimiech** [comment]
Let's only add these (worded in this way)

Philanthropy/E2G
Public policy/Politics
Public speaking
Recruitment
Entrepreneurship (if not there yet)
Event planning
Finance
Graphic design
Journalism
Law
Management
Marketing/Communication

and discard the rest

**Comment by taymonbeal** [comment]
So the mapping thus far looks like this:

|Legacy|New|
|---|---|
|Coding|Software engineering|
|Entrepreneurship|Entrepreneurship|
|Event planning|Event planning*|
|Finance/Investment strategy|Finance*|
|Graphic design|Graphic design*|
|Journalism|Journalism*|
|Law|Law*|
|Management|Management|
|Marketing/Sales|Communications|
|Philanthropy|Philanthropy, earning to give*|
|Public policy/Politics|Government and policy|
|Public speaking|Public speaking*|
|Recruitment|Recruitment*|
|Research/Analysis|Research|
|Statistics/Data science|Math, quant, stats expertise|

Asterisk means that this option doesn't already exist and will have to be newly added.

The legacy areas not in the above table are:
- Mentoring
- Networking/Schmoozing
- Organizing groups/teams
- Outreach
- PR
- Persuasion
- Strategy
- Video production
- Web development

The new areas not in the above table are:
- Operations
- AI technical expertise
- Economics, quantitative social science
- Movement building
- Philosophy
- Humanities
- Psychology
- Physics
- Medicine
- Other science

Also, should we put things in the "other" field if they're not in any of our supported categories? Either the listed ones or the freeform ones?

**Comment by michaltrzesimiech** [comment]
The mapping looks good. We should drop the remaining legacy areas and keep the new areas not included in the mapping table. Keeping those areas in the "other" field sounds like a very good solution.
