### ISSUE TITLE
Unbreak old links to profiles

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#428]
If we care about this, we have to put it into place now, before those old URLs potentially get claimed by new users.

**Comment by michaltrzesimiech** [comment]
I'd say it's a secondary priority which means we could do without it

**Comment by taymonbeal** [comment]
Are we okay with running the risk that someone claims a URL that belonged to a different person on the old Hub? That would force us to choose whose links to break.

**Comment by taymonbeal** [comment]
If we're okay with that possibility we can postpone this.

**Comment by michaltrzesimiech** [comment]
Are we speaking about the URLs for groups or persons or both?

**Comment by taymonbeal** [comment]
My primary concern is about persons. It'd also be nice to not break groups, but those have always had more active management and we can import/change things later if desired.

**Comment by michaltrzesimiech** [comment]
Ok, so after giving it a thought (and going through that pile of broken INTERNAL link emails), I currently think that we're best to unbreak the URLs, at least for persons.

**Comment by Richenda** [comment]
I think the decision is made ^ and this can be acted on now :)

**Comment by taymonbeal** [comment]
Is it okay if the actual unbreaking of the links waits until post-launch? I've implemented the part that (for technical reasons) has to happen pre-launch, but not yet the rest of it.

**Comment by michaltrzesimiech** [comment]
I guess this may depend on whether we will import the historical profiles. If we want to do that, I think it's better to delay the launch but have the profiles in and the links unbroken?

**Comment by taymonbeal** [comment]
Copying comments from Slack:

Basically all the work needed to support importing the old profiles has been done. The old usernames and aliases will be present in the database.

The URL paths are currently different from the old ones, so we'd need to set up redirects from the old ones to the new ones. We'd also need to add redirect support from aliases and from the old database IDs. But from a technical perspective, these aren't database changes and can be made post-launch if desired.

The thing we needed to do pre-launch was import the data backing the old URLs and make sure people can't squat on each other's usernames. That part's done.

**Comment by michaltrzesimiech** [comment]
Sorry, I didn't get it the first time. Sure, we're free to do that post launch.

**Comment by taymonbeal** [comment]
These look like `/user/<slug>` and `/user/<int>`.

**Comment by taymonbeal** [comment]
Next steps here are:
- Make sure that when a user is deleted their slug remains in the database
- Import all the old slugs
- Import the legacy database IDs as slugs

**Comment by taymonbeal** [comment]
Actually that's not a good plan; deleted users should be completely gone. Instead we can insert tombstone slugs on an ad-hoc basis to get rid of 404 alerting for spam queries.

**Comment by taymonbeal** [comment]
Even simpler, let's just not alert on lookup failures.
