### ISSUE TITLE
Don't make people log in immediately after a password reset

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#433]

**Comment by taymonbeal** [comment]
For the initial round of reset emails in particular, we want people to be taken straight to their profile-editing page as soon as they've set their new password.

**Comment by Manoj-nathwani** [comment]
I'm unable to get my local sack working so I can't work on this however I think it's as easy as:

1. Create a new view with `name='password_reset_done'` which will over-ride the priority of the default view django sends users to after resetting their password.
2. In the new view simply add a django redirect to `return redirect('edit_profile')` which will send users to your desired url.

**Comment by Manoj-nathwani** [comment]
@taymonbeal  I'm unable to get my local sack working so I can't work on this however I think it's as easy as:

1. Create a new view with `name='password_reset_done'` which will over-ride the priority of the default view django sends users to after resetting their password.
2. In the new view simply add a django redirect to `return redirect('edit_profile')` which will send users to your desired url.

**Comment by taymonbeal** [comment]
It's not quite that simple, because the user won't actually be logged in at that point, so they'll get bounced back to the login screen. But I think there's an option to fix that.
