### ISSUE TITLE
Make private profiles visually distinct

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#435]
It's easy to miss, when looking at a profile as a superuser or as its owner, that it's been made private. It'd be good to make these visually distinct on the list and detail pages.

**Comment by michaltrzesimiech** [comment]
I agree. Any simple solution will do for the first iteration (i.e. adding "*" to name). I'd say it's not blocking the announcement because it's not affecting the wider public. It's definitely good to have it asap.
