### ISSUE TITLE
Empty info box on change password and wrong title

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#441]
![Screen Shot 2019-03-17 at 18 29 00](https://user-images.githubusercontent.com/15908208/54496059-a0da9880-48e2-11e9-8a95-5036b2afdb7c.png)

**Comment by taymonbeal** [comment]
This has the same underlying cause as #345.

**Comment by taymonbeal** [comment]
Wait, no, that's wrong, I misunderstood.

**Comment by taymonbeal** [comment]
Ok, the culprit is actually https://stackoverflow.com/a/5681796/1064659.
