### ISSUE TITLE
Figure out how future milestones/prioritization work

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#443]

**Comment by michaltrzesimiech** [comment]
Is this still a thing that we want to formalize?

**Comment by taymonbeal** [comment]
Probably? At least we should figure out what the due dates and such on the milestones mean, if we're going to keep having those.

**Comment by taymonbeal** [comment]
This is still an open issue. Like, what does it mean that Plato is due on May 10?

**Comment by taymonbeal** [comment]
Sounds like we want time-based marketing releases. Would we want to announce these in any existing newsletters? If so, we'd have to time deadlines to match up with those releases.

**Comment by taymonbeal** [comment]
We'll make a new newsletter for this.
