### ISSUE TITLE
No character limit on usernames

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#451]
Allowed me to create an account with username Testtesttesttesttesttesttesttesttesttesttesttesttesttesttesttesttest

![image](https://user-images.githubusercontent.com/14195560/54547973-258eea80-49a7-11e9-9242-83458b857ac3.png)

**Comment by taymonbeal** [comment]
There totally is a limit, it's 200 characters. That's only 68.

**Comment by michaltrzesimiech** [comment]
Yes, I tried with more and it got cut. I think 200 is a bit too much even for an elaborate number of names and surnames some people may prefer to use. I'd say 50 is enough, though the priority of this is the lowest possible.

**Comment by taymonbeal** [comment]
I think the solution to this kind of issue is a combination of "moderate spammy/inappropriate profiles" and "design the page layout such that even pathological inputs can't mess it up too badly", rather than applying stricter input limits to everything.

**Comment by sebgrebe** [comment]
I can slap a word-break on the username to prevent it from over running
