### ISSUE TITLE
Implement SPAM detection, eg by rolling back to recaptcha v2 and adding v3 later on

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#459]

**Comment by taymonbeal** [comment]
What's the use case here? Is it prevention of automated spam, or something else?

**Comment by michaltrzesimiech** [comment]
We seem to have cases of bogus accounts and I'm afraid that these will be back after we delete them. Blocking by IP or whatever makes more sense could also be useful, also for blocking automated spam after we introduce messaging. And also, after we add the "report abuse" button, we should have a flow for excluding users, ideally with some audit trail.

**Comment by taymonbeal** [comment]
I suspect we should use an actual spam detection API like Akismet for this.

**Comment by taymonbeal** [comment]
What of this do we actually need before the freeze?

**Comment by michaltrzesimiech** [comment]
A spam detection API would be great. Based on what we observed so far, we've had something like 5 new spam profiles created since the official launch. We can control this amount manually, so this can be postponed until post-freeze.

**Comment by michaltrzesimiech** [comment]
Prioritizing this for https://github.com/rtcharity/eahub.org/milestone/8 since this issue will affect that.

**Comment by sebgrebe** [comment]
Need to add spam report buttons for admins as discussed here

![Screen Shot 2019-08-23 at 16 49 02](https://user-images.githubusercontent.com/15908208/63605480-f3249180-c5c5-11e9-9eda-096fdb914eed.png)

**Comment by sebgrebe** [comment]
What should happen on clicking this button? Email sent to admins?

**Comment by taymonbeal** [comment]
It should delete the item and send it to Akismet as an example of spam. In order to do the latter, we need to integrate Akismet.

**Comment by michaltrzesimiech** [comment]
We should prioritise this higher since the manual maintenance costs accumulate with each month

**Comment by vagarwalla** [comment]
Some users were blocked because the wrong pattern was blocked (e.g. .info/.iu)

**Comment by victor-yunenko** [comment]
It has been deployed and tested.

We have a new google admin now. I can add more google accounts on request.
