### ISSUE TITLE
How should we treat links in custom text fields?

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#461]
Should we allow links (i.e. by validating against a regex)? If so, should we automatically turn them into hyperlinks?

![image](https://user-images.githubusercontent.com/14195560/54608067-3ba4b580-4a50-11e9-9393-75361a6be7ca.png)

**Comment by taymonbeal** [comment]
This is part of a bigger question around text formatting.

Do we envision people ever entering multiple paragraphs here? I think right now the UI allows it but the page layout isn't very optimized for it. Maybe this is different for different fields?

**Comment by taymonbeal** [comment]
Bumping the priority of this because it has implications for legacy profiles, some of which include rich text.

**Comment by sebgrebe** [comment]
Allowing for link seems sensible (if this is not a security issue). Turning all links on the profile page into hyperlinks is two lines of code.

**Comment by sebgrebe** [comment]
Made a PR that adds the hyperlinks in case we want to go with this: #470

**Comment by taymonbeal** [comment]
The way im

**Comment by taymonbeal** [comment]
The way I'm currently leaning towards handling this is allowing Markdown in multiline text fields. Do people feel that this makes sense?

**Comment by sebgrebe** [comment]
I guess this would conflict with automatically turning URLs (using linkify) into links as linkify would turn the markdowned URLS into html, wouldn't it?

I think one disadvantage of using markdown is that most users won't be familiar with the syntax?

**Comment by taymonbeal** [comment]
Markdown automatically turns URLs into links.

**Comment by sebgrebe** [comment]
I know, but if we also have linkify, then that creates a mess (I think). What I'm saying is that we can't have both and if we implement markdown and not linkify and people don't know how to use markdown, then we don't have linkified URLs.

**Comment by taymonbeal** [comment]
If they just enter URLs and they get Markdown processed then they'll appear as links.

**Comment by sebgrebe** [comment]
I thought with markdown you need to do it like this:
```[name of site](www.site.com)```
or is that only github's markdown?

**Comment by sebgrebe** [comment]
www.test.com

**Comment by taymonbeal** [comment]
Yes, that's how you make a link with custom text, but if you just enter a raw URL Markdown renders it as a link too. In general Markdown is designed to do something reasonable even if users aren't familiar with the syntax.

Although it actually looks like not all Markdown implementations do this, so we'd want to use one that does.

**Comment by sebgrebe** [comment]
just looking for a library/package that applies markdown to html, let me know if you know of any from the top of your head

**Comment by taymonbeal** [comment]
We're going to want to do this server-side in Django.

**Comment by sebgrebe** [comment]
OK. Should we stick with linkify for pre-launch and then change later or are you confident that this can be implemented before Monday (including all the other stuff that needs to be done by then)?

**Comment by taymonbeal** [comment]
This needs to be part of the data migration because that includes rich text that we'll want to carry over. Otherwise I'd say this could wait until post-launch.

**Comment by sebgrebe** [comment]
I'll remove my PR

**Comment by taymonbeal** [comment]
We can't wait until Plato to decide whether to support rich text. We have to make that decision now, because it's part of the data migration.

**Comment by taymonbeal** [comment]
Change of plans. @Richenda says we don't want to support rich text. So go ahead with the Linkify thing.

**Comment by taymonbeal** [comment]
(Also we should really be doing this server-side, but that can wait. Like, forever.)
