### ISSUE TITLE
Group profile: Consistently use N/A

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#467]
![Screen Shot 2019-03-21 at 20 30 10](https://user-images.githubusercontent.com/15908208/54783067-56c22180-4c18-11e9-81c3-d4a5d890a54b.png)

**Comment by Richenda** [comment]
So with this, originally I asked for us to have a function that hides a category if the user doesn't fill it in. Do you know what happened with that? Was it forgot or did we move away from it for some practical reason? @Manoj-nathwani  This was like... December.

**Comment by taymonbeal** [comment]
That's completely straightforward technically, so I'd guess that it was simply forgotten.

**Comment by Richenda** [comment]
Well it was agreed on during a time when you weren't active in the discussions, so Seb and Manoj might have other details to share on this.

**Comment by sebgrebe** [comment]
@taymonbeal is right, we simply forgot. I'll get on it, it looks ugly and bugs me :)
