### ISSUE TITLE
Specify terms for third-party reuse of data

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#468]
Other people might wonder whether they can reuse the data that's public on the EA Hub for whatever purposes.

We need to figure this out pre-launch because whatever terms we have for this need to be binding on users who submit data.

**Comment by Richenda** [comment]
I'll leave this for Michal because I don't know what the current data policy says in detail. The complexity here is that I would prefer no third party use of current Hub data but we should allow third party use of EA Survey data which I hope we will some day be supplying for general use on the Hub.

**Comment by taymonbeal** [comment]
If we were to go with that solution, then I don't think it would be necessary at this time to change anything.

**Comment by taymonbeal** [comment]
Correction: We would need to update the footer text to make clear that the MIT License applies only to the stuff on GitHub, not the stuff in the database.

**Comment by michaltrzesimiech** [comment]
This sounds good.
