### ISSUE TITLE
SMTPServerDisconnected exception

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#473]
This is causing people claiming groups to see 500 errors, and also means we don't get notified about said errors.

**Comment by taymonbeal** [comment]
As I suspected, the problem is that we ran out of quota. I'm addressing this in #163. I've created us a new SendGrid account with more quota through the Azure Marketplace, but before I finish setting it up I need to figure out how to make it play nice with Migadu. @michaltrzesimiech, please provide instructions on how to access Migadu as soon as you get the chance.

**Comment by michaltrzesimiech** [comment]
Thanks for investigating this! Shared the password with you through LastPass.

**Comment by taymonbeal** [comment]
I think I've fixed this.
