### ISSUE TITLE
Browser support policy

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#475]
Do we care about IE?

**Comment by taymonbeal** [comment]
Note that in principle we can have "it works but without all the fancy frontend features" as a level of support for older or less-popular browsers, if desired.

**Comment by michaltrzesimiech** [comment]
1.06% of our users so far use(d) IE (that's 9 users). Given the costs, I'd say we should prioritize support for IE  low enough that we could close this issue and reopen it once more users choose IE.

**Comment by taymonbeal** [comment]
Is it okay if the site is just arbitrarily broken for users with unsupported browsers, or should we try to facilitate some kind of graceful degradation?

**Comment by michaltrzesimiech** [comment]
Not sure how this could look like. I'd imagine we could display a banner saying that `Your browser is currently unsupported and some functions of the website might not work as expected.`

**Comment by taymonbeal** [comment]
We could do that. We could also disable JavaScript on all unsupported browsers; they could still access the site but without in-browser interactive features. Or we could just say that whatever happens happens.

**Comment by michaltrzesimiech** [comment]
+1

**Comment by taymonbeal** [comment]
I meant we should pick one of those options.

**Comment by michaltrzesimiech** [comment]
I actually thought of both (that we could disable JS on all unsupported browsers and put up the banner).

**Comment by taymonbeal** [comment]
Ok, works for me.
