### ISSUE TITLE
Group organisers should automatically become members of groups

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#488]
If a user is assigned as the organiser of a group, they should automatically become members of that group. At the moment, it's possible to be organiser, but not member

**Comment by taymonbeal** [comment]
I'll note that there are various reasons why this is complicated. Like, someone else can add you as an organiser.

**Comment by taymonbeal** [comment]
How come we closed this?

**Comment by michaltrzesimiech** [comment]
Based on your previous comment, I decided we don't really want that. Should we reconsider this for any reason?

**Comment by taymonbeal** [comment]
I think the direction I want this to go in is to get rid of the separation between "users" and "profiles" (yes that was my idea in the first place but experience has convinced me that I was wrong; sorry about that), and instead have a many-to-many relationship expressing the relationship between groups and organizers, which could be "non-member", "member", "organizer", "former organizer", "blocked", "banned", or any number of other things that we might add in future. This is going to require a bit of refactoring work though, so I'd wait until it was blocking something we care about.

**Comment by michaltrzesimiech** [comment]
Sounds good. Prioritising as an improvement to groups (currently, January 2020).
