### ISSUE TITLE
Find a way to filter out and truncate spam/fake accounts in legacy profiles

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#497]
![image](https://user-images.githubusercontent.com/14195560/54944236-55079f00-4f33-11e9-8a10-d0c91f48ddb4.png)

**Comment by taymonbeal** [comment]
Do we need to do this pre-launch/before running the data import?

**Comment by michaltrzesimiech** [comment]
No, we can do this after we import the data (since none of these will be visible to end users until the owners of those accounts claim them, which in case of some of these accounts is unlikely).

**Comment by michaltrzesimiech** [comment]
Actually, we will have to identify at least a portion of fake accounts to send out the reclaim links. I deleted some of these manually.

**Comment by michaltrzesimiech** [comment]
(Since Mar 26 I deleted a bunch more of these)

**Comment by michaltrzesimiech** [comment]
I manually sieved through all of our accounts. Closing as done.
