### ISSUE TITLE
Set minimum number of chars in a username to 2, disallow the use of a special sign as a first char

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#498]
![image](https://user-images.githubusercontent.com/14195560/54944669-508fb600-4f34-11e9-8060-d82c99e23a34.png)

**Comment by taymonbeal** [comment]
Is this just for spam prevention? If so, I'm inclined to close it in favor of a more general anti-spam solution.

**Comment by michaltrzesimiech** [comment]
We could do that
