### ISSUE TITLE
The initial search in input#filterbox in /profiles/ takes a long time to return results

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#500]
Might only be true for a ngrok session, not true for production.

![image](https://user-images.githubusercontent.com/14195560/54945164-7ff2f280-4f35-11e9-853d-d293800836f6.png)

**Comment by taymonbeal** [comment]
I think that search happens entirely client-side.

**Comment by michaltrzesimiech** [comment]
Me too. Chrome 72.0.3626.121 64-bit; Windows 7; Intel i7-4510U @ 2.00GHz; 8GB RAM.

**Comment by michaltrzesimiech** [comment]
Yep, it's currently veeery slow

**Comment by taymonbeal** [comment]
Mind trying this in an incognito window? I bet it's a lot faster for people who can't see the thousands of private profiles (in which case this becomes a lot less urgent).

**Comment by michaltrzesimiech** [comment]
It is much faster for a limited number of accounts. I agree that it's not necessarily of high time-priority, but it is still of high importance priority to us.

**Comment by victor-yunenko** [comment]
Since we're working on the new search (most likely based on Algolia or another search engine), I'll close this ticket in favor of #958. Please feel free to reopen if needed 👌
