### ISSUE TITLE
Bad request for deleting all records of a given type

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#504]
Used https://eahub.org/admin/base/user/?p=0&q=.pl 

![image](https://user-images.githubusercontent.com/14195560/54986897-c4bd6e80-4fb3-11e9-8d7b-599e372e9140.png)

**Comment by taymonbeal** [comment]
How many records did you attempt to delete at once when you got this error?

**Comment by michaltrzesimiech** [comment]
>100. Tried now for 784 and it worked.
