### ISSUE TITLE
Improve the appearance of the bottom section of profile/signup/

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#513]
![image](https://user-images.githubusercontent.com/14195560/55102103-f1fa4180-50c5-11e9-99b6-80fd46b5d59b.png)

**Comment by sebgrebe** [comment]
@michaltrzesimiech what in particular? More spacing?

**Comment by michaltrzesimiech** [comment]
Ah, yes! Just some extra space would be enough. Allowing that text to sit in a single line could also work well.
