### ISSUE TITLE
Create procedures for emergency production changes

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#515]
This is a tradeoff between allowing production emergencies to be mitigated quickly, especially when only one developer may be awake to resolve it, vs. reducing risk associated with an account compromise. I'm not certain what's the right way to handle it.

**Comment by michaltrzesimiech** [comment]
I'd generally trust that the hard requirement of having 2FA enabled on GitHub, LastPass and Azure for anyone to handle such emergencies is enough to begin with.

**Comment by taymonbeal** [comment]
We've decided not to create any exceptions for emergency production changes. All changes should require review by two members of the tech team. This may be revisited if we can't keep up our availability SLO.
