### ISSUE TITLE
Send out the launch emails

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#516]
- [x] 08:00 UTC: Send emails to testers.
- [x] 09:00 UTC: Send emails to a random 10% of European users.
- [x] 10:00 UTC: Send emails to remaining European users.
- [x] 18:00 UTC: Send emails to everyone else.

**Comment by taymonbeal** [comment]
This is happening tomorrow, April 8.

**Comment by michaltrzesimiech** [comment]
Our tester confirmed to have received the email and claimed the account back without issues

**Comment by taymonbeal** [comment]
Mission accomplished. We're launched.
