### ISSUE TITLE
Improve experience of account reactivation without email

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#517]
Our new launch plan means that people are going to encounter the site without having necessarily received their reactivation emails. We need them to have a smooth onboarding experience in that case.

**Comment by taymonbeal** [comment]
When somebody tries to register an account with an email that's already in the database, they should be prompted to recover their account.

Social login would make this a _lot_ smoother, because without it we have to send them an email.

**Comment by michaltrzesimiech** [comment]
+1

**Comment by michaltrzesimiech** [comment]
> Social login would make this a lot smoother, because without it we have to send them an email.

While I think this is true in general, I think that there would be users that would prefer alternatives to social

**Comment by Manoj-nathwani** [comment]
https://auth0.com Is awesome for doing auth in general and would allow us to have both social & regular email/password auth flows running side-by-side 🤔

**Comment by taymonbeal** [comment]
There was some [earlier discussion](https://github.com/rtcharity/eahub.org/issues/345#issuecomment-473398197) of auth0; feel free to weigh in. The current thing I've been doing is integrating django-allauth, which is the most popular authentication package in the Django ecosystem and which also allows social and regular flows side-by-side. We would also need it or something like it in order to use auth0. Basically, my thinking was that this is probably going to be the foundation of whatever we wind up doing for auth, so we might as well get it in place now.

**Comment by taymonbeal** [comment]
I think the first decision we need to make is a security-vs.-usability tradeoff: Is it okay if an attacker can find out whether a particular email address has an account? Does it make a difference if the user is notified if this occurs? This affects a bunch of other stuff about the design of this flow.

**Comment by taymonbeal** [comment]
I've split this into a bunch of sub-issues; I'll close it when #532 merges.
