### ISSUE TITLE
Point /groups/get-a-website to github.com/rtcharity/lean-site-template

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#521]
Based on 

> Referrer: https://effektiveraltruismus.de Requested URL: /groups/get-a-website User agent: Mozilla/5.0 (compatible; MSIE 9.0; Windows NT 6.1; WOW64; Trident/5.0) IP address: 149.126.4.71, 162.158.150.57:28966

**Comment by taymonbeal** [comment]
Duplicate of #609.
