### ISSUE TITLE
Bring back /files

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#523]
How hard will it be for us to bring back /files? It looks like a number of external sites might depend on that path (mostly archival content)

> Referrer: https://sloangroups.mit.edu/EffectiveAlt/blog/effective-altruism-newsletter/6428/ Requested URL: /sites/eahub.org/files/Logo_large.jpg User agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/73.0.3683.86 Safari/537.36

**Comment by taymonbeal** [comment]
I've actually reached out to Sloan about getting them to fix their website, but that's probably not going to happen.

Restoring this should be doable one way or another, but first we should figure out where we want these files to move to. Would we just check them into Git, or is there some other file management solution we've been thinking of?

**Comment by victor-yunenko** [comment]
Probably it isn't actually anymore since in a year all the links that could have been replaced have been replaced? I'll close this ticket then, please feel free to reopen if needed.
