### ISSUE TITLE
Make the table in /groups customizable

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#525]
We should let users decide what parameters (like size, location, status) are interesting to them and so add or remove criteria. Ideally, they should be also able to rearrange the order (but that's a nice-to-have).

**Comment by patbl** [comment]
This doesn't seem especially useful to me. Location is essential, so that should always be included. Once you narrow it down by location, there will probably be just a handful of groups. Also, I don't see size information. That seems like it would fluctuate anyway.

Are inactive groups displayed anymore? My understanding was that @cafelow [got rid of them](https://rtcharity.slack.com/archives/CHF7NEM8U/p1576720733002200).

**Comment by cafelow** [comment]
Hey @patbl and @michaltrzesimiech,
1. I've mostly deleted inactive groups - but there are still some groups where people have recently changed their group to "inactive" and these groups are still on the hub. The reason we haven't deleted inactive groups is that in theory people could still contact the old organiser to get any mailing lists or advice if they want to start a group in that area (assuming there is an organiser listed). The other reason people might want non-existent groups to be displayed is that if there is one potential organiser, but they don't want to start a group unless they have a co-organiser help them. There may be other reasons that I can't think of. 
So what I would REALLY like to have these categories (don't know what the suitable names are)
a. Active
b. Previous group (contact old organiser for help if you want to start a group in this area). 
c. Potential group (contact potential organiser if you want to help start a group in this area). 

2. I agree that we don't want to ask group organisers for too much information that could possibly fluctuate, as it could get out of date quickly. But I WOULD really like some free text (with hyperlinks). There are several groups who have youtube channels or twitter, or other social media accounts that they've given us in the Local Group Survey, but we aren't currently able to share. This free text could also give people an opportunity to share more information about the group or just a friendly greeting. 
 
3. I WOULD really like the types of groups to have more flexibility as many groups don't fit nicely into the categories listed. I was going to start a github issue about this but I forgot, I will do this now.
