### ISSUE TITLE
Provisionally integrate smooch.io

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#544]

**Comment by michaltrzesimiech** [comment]
I need to organize and send the documentation that proves our charity status. This might take a while, but shouldn't block our launch.

> The Community Plan includes 5,000 conversations per month. If you go over your monthly limit, you will continue to receive all messages. However, you will not be able to send any messages until you get in touch with us. If you reach your limit, or if you think you’ll need more than 5,000 conversations per month, let us know and we’ll work something out for you.

**Comment by michaltrzesimiech** [comment]
An update on this: sent the link to save on time https://apps.cra-arc.gc.ca/ebci/haip/srch/charity-eng.action?&bn=793187881RR0001

**Comment by taymonbeal** [comment]
Yeah, I figure we'll be on the free trial until this gets sorted.

**Comment by michaltrzesimiech** [comment]
The trial is 14 days, everything is ready on the back end. Shared the details with everyone with the access to the correct LastPass folder.
