### ISSUE TITLE
On feedback.eahub.org/, clicking on the logo should take me back to the Hub

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#554]
On feedback.eahub.org/, clicking on the logo should take me back to the Hub, or there should be another easy way for me to get back

**Comment by michaltrzesimiech** [comment]
There is no way to configure that out of the box in Fider. We can only make sure that the links are target="_blank".

**Comment by taymonbeal** [comment]
It might be possible to resolve this by hacking Fider.
