### ISSUE TITLE
On paginated lists, going to another page should make the view jump back to the top

### ISSUE THREAD

**Issue by ohmoses** [rtcharity/eahub.org#569]
Currently, when I navigate to another page on paginated lists (/profiles and /groups), the view stays scrolled all the way down to the bottom of the page. I would expect the view to jump back up to the top of the page.

**Comment by victor-yunenko** [comment]
It's definitely a good point 👍 

Since we're moving to [the new faceted search](https://eahub-stage.us.aldryn.io/profiles/) (for profiles & groups) with infinite loading I guess we're going to resolve it by default :) ? I'll close this ticket then 👌
