### ISSUE TITLE
Link to the job board by 80,000 Hours

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#571]
Based on: https://forum.effectivealtruism.org/posts/2LpW22MpmAPuiraJt/announcing-ea-hub-2-0#4WdCwSm7hfdfshNEJ

**Comment by michaltrzesimiech** [comment]
@Richenda how to go about adding 80,000 Hours job board so that it makes the most sense UX wise?

**Comment by Richenda** [comment]
Posting here for benefit of everyone... I would create a new icon on the home page and attach it to a redirect.

**Comment by michaltrzesimiech** [comment]
+1 @Richenda

**Comment by sebgrebe** [comment]
@Richenda 
Oo we have an icon for this? 
Or could we just use the 80k logo or do we get copy right issue with this? (Also, wouldn't fit too nicely into the existing design, I guess)

**Comment by sebgrebe** [comment]
Could look worse, I guess. Could someone check with 80k whether we're allowed to use their logo (and adapt it to our design)?

![Screen Shot 2019-08-23 at 17 34 24](https://user-images.githubusercontent.com/15908208/63608194-47cb0b00-c5cc-11e9-8586-e181ac9f843c.png)

**Comment by michaltrzesimiech** [comment]
Let's keep a single button that's "EA Work & Volunteering" that takes us to a page with 2 hyperlinks: one to 80,000 Hours job board, the other one to EA Work Club. Soon, there's going to be a new org like that and we may want to add links as we go. The target page can be hosted on resources.eahub.org (but doesn't have to be hosted there).

**Comment by Richenda** [comment]
> Let's keep a single button that's "EA Work & Volunteering" that takes us to a page with 2 hyperlinks: one to 80,000 Hours job board, the other one to EA Work Club. Soon, there's going to be a new org like that and we may want to add links as we go. The target page can be hosted on resources.eahub.org (but doesn't have to be hosted there).

I agree with this approach.
I want to support the Work Club equally. And in the past CEA tried to squish that thing out. So I don't want the Hub to pick a favourite like that but give people neutral exposure to all the options. Is that ok?

**Comment by sebgrebe** [comment]
I see your point about not signalling preference of 80k job board over the work club. But couldn't we achieve this by simply having both of the buttons there? Maybe change 'EA Work & Volunteering' to 'EA Work Club'? Having to click on a button and then be redirected to another page which just contains two links is not great UX

**Comment by Richenda** [comment]
Yeh, that’s fine by me. I do think we have to speak to 80k before assigning them an icon. After that it’s a 1 hr job for me to prep an icon.

**Comment by sebgrebe** [comment]
> Yeh, that’s fine by me. I do think we have to speak to 80k before assigning them an icon. After that it’s a 1 hr job for me to prep an icon.

@Richenda @michaltrzesimiech Who could get in touch with them?

**Comment by Richenda** [comment]
@sebgrebe it has to be @michaltrzesimiech 
For diplomacy reasons!

**Comment by michaltrzesimiech** [comment]
I'll ask their permission

**Comment by michaltrzesimiech** [comment]
> Hi Michael,
> 
> Yeah that's totally fine. Thanks for checking!
> 
> Best,
> Keiran.
>
