### ISSUE TITLE
Consider users who disabled webfonts

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#575]
> [The Hub uses] webfonts for some of its graphics and is therefore annoying and possible partially inaccessible for people who have webfonts disabled due to wanting to avoid the blurry and often unreadable fonts that are far too commonly used nowadays (even if this website does not use such fonts, it is not easily possible to selectively disabled web fonts for only some websites). I would hope that you are rational enough to rethink this design decision.

**Comment by taymonbeal** [comment]
What browser, and what setting was used to disable web fonts?

**Comment by michaltrzesimiech** [comment]
Asking the user

**Comment by patbl** [comment]
I think it's weird that someone would disable Web fonts because they found them "blurry and often unreadable" and then complain that they don't like how the site looks with them disabled. Web fonts are pretty standard these days.
