### ISSUE TITLE
Move smooch conversations away from email

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#576]

**Comment by taymonbeal** [comment]
If you could have this work however you wanted, what would the workflow be?

**Comment by michaltrzesimiech** [comment]
There are so little of these we may as well keep them this way. Once we do https://github.com/rtcharity/eahub.org/issues/691, it shouldn't be a big problem to monitor the mailbox.

**Comment by taymonbeal** [comment]
Do we even want to keep Smooch online?
