### ISSUE TITLE
Specify availability requirements

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#579]
I'd like to know how much downtime, and in particular how much MTTR, we're willing to tolerate, so we can discuss what we have to do to stay within the resulting [error budget](https://landing.google.com/sre/sre-book/chapters/embracing-risk/).

**Comment by michaltrzesimiech** [comment]
Do we currently have insight into how much downtime we face nowadays?

**Comment by taymonbeal** [comment]
Current proposal: Aim for 99% availability, no latency or throughput SLO yet.
