### ISSUE TITLE
GeocoderServiceError at /profile/edit [Errno 99] Cannot assign requested address

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#582]
This has come up a few times now. It seems to be intermittent.

Reluctantly not calling this a production emergency because we probably can't fix it in a short time. :-(

Maybe moving away from Nominatim will help?

**Comment by patbl** [comment]
#844 migrates away from Nominatim.

**Comment by vagarwalla** [comment]
Closed because weren't able to reproduce for the last several months.
