### ISSUE TITLE
Make it mandatory for Organizers' profiles to be public before they can claim a group

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#585]
the Organiser we set for /group/effektiver-altruismus-zrich is not displayed on https://eahub.org/group/effektiver-altruismus-zrich, but it is being shown in the Organisers personal profile.

**Comment by taymonbeal** [comment]
Working as designed. The user's profile is private, so we don't show it on the page.

**Comment by michaltrzesimiech** [comment]
Thanks! I'll reply with that info

**Comment by taymonbeal** [comment]
Do we want organisers to be able to have private profiles at all, in general?

**Comment by michaltrzesimiech** [comment]
Not sure how to bring those two requirements together. We want groups that have orgnisers to list their names publicly. We also want organisers to be able to have private profiles in general. We could overcome this by masking their identity but making it known that the group has been claimed (and making sure that there's a way to contact the anonymous organiser, so i.e. making it a requirement that there be an email, or making it possible [in the future] to contact the anonymous organiser)
