### ISSUE TITLE
Break down the requirements for the projects module

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#587]

**Comment by michaltrzesimiech** [comment]
We should start with integrating this spreadsheet https://docs.google.com/spreadsheets/d/1yzmg02j8PnvjlV_KX3Vf_u9TNdAS63N-9xy2txmTg-A/edit#gid=957019158

**Comment by herwix** [comment]
Just throwing in a small idea: One simple thing that could be done to get some more information about what information people would like to have about projects would be to do something like a customer survey about the spreadsheet. Should be easy enough to set up and may be a good thing to do before/with the launch. Could most likely help out with this.

**Comment by Richenda** [comment]
Good idea

**Comment by michaltrzesimiech** [comment]
+1
