### ISSUE TITLE
navbar-menu doesn't close when onclick elsewhere

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#590]

**Comment by Manoj-nathwani** [comment]
https://getbootstrap.com/docs/3.3/examples/theme/
This is just a basic bootstrap feature. It it really a "bug"?

**Comment by sebgrebe** [comment]
> https://getbootstrap.com/docs/3.3/examples/theme/

@Manoj-nathwani are you saying that it's okay and we should leave it?

I find it annoying and we had users complain about it.

**Comment by michaltrzesimiech** [comment]
It's true though that we don't necessarily have to prioritize it for the freeze period. Moved it to Plato (hope I didn't do that too late).

**Comment by sebgrebe** [comment]
> It's true though that we don't necessarily have to prioritize it for the freeze period. Moved it to Plato (hope I didn't do that too late).

No, not too late :)
