### ISSUE TITLE
A record of number of people registered over time

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#595]
As mentioned in here https://forum.effectivealtruism.org/posts/2LpW22MpmAPuiraJt/announcing-ea-hub-2-0#Z7psWrjRcdDdDdMz6

**Comment by taymonbeal** [comment]
Do you want this as a one-off report that I just run against the database, or something that's more like an actual feature?

**Comment by michaltrzesimiech** [comment]
No, it's just a one-off report at this point

**Comment by taymonbeal** [comment]
Okay, do we want this as of any particular moment in time?

**Comment by michaltrzesimiech** [comment]
I'd say from the launch till now. If we could somehow (cheaply) restore/estimate the data from the old Hub, that would be ideal.

**Comment by taymonbeal** [comment]
The registration dates from the old Hub are in the new database. Except, of course, for those belonging to users whom we purged as spam.

Note that reactivation dates of existing accounts are *not* in the new database, though most recent login dates are.

**Comment by michaltrzesimiech** [comment]
We should go the easy way and just count the growth of unique users.

**Comment by taymonbeal** [comment]
I can pretty straightforwardly get a graph of user registrations over time. However, it will include _all_ the users still in the database, many of which are believed to be spam.

**Comment by michaltrzesimiech** [comment]
That's ok, at least until we figure out https://github.com/rtcharity/eahub.org/issues/497

**Comment by patbl** [comment]
I think the link in the description is wrong, and this is probably the correct one: https://forum.effectivealtruism.org/posts/2LpW22MpmAPuiraJt/announcing-ea-hub-2-0?commentId=NWdpJCBGuELcghpXZ

**Comment by victor-yunenko** [comment]
I would say it's been handled by the profile logs. Please feel free to reopen if needed.
