### ISSUE TITLE
Figure out how to send marketing emails

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#597]
The first question that comes to mind is whether to do it in Django or use a full-service email marketing platform like Mailchimp. Both options have advantages and disadvantages. The full-service platform may offer better deliverability and will likely make it easier to create mail campaigns without requiring developer time, but at the cost of complicating the story of how the subscriber list interacts with the main account management system.

This needs to get nailed down before the freeze because we're going to send our first marketing email (the Plato announcement) during the freeze.

**Comment by michaltrzesimiech** [comment]
We should target building a smooth flow involving our Mailchimp and only treat our Django setup as tactical/temporary.

**Comment by taymonbeal** [comment]
Okay, Mailchimp it is. This means that users' subscription preferences will live in Mailchimp's database, not ours.

How should the subscription flow work? The simplest option is to just embed a Mailchimp signup form on our site somewhere. For a bit of additional complexity cost, we can also auto-sign-up people when they create accounts if they checked the box on the registration form. For rather more additional complexity cost, we can allow users to subscribe and unsubscribe from the settings page.

The subscription database column is going away, but of course we'll export the existing email addresses from it and load them into Mailchimp.

**Comment by michaltrzesimiech** [comment]
> How should the subscription flow work? The simplest option is to just embed a Mailchimp signup form on our site somewhere. For a bit of additional complexity cost, we can also auto-sign-up people when they create accounts if they checked the box on the registration form. For rather more additional complexity cost, we can allow users to subscribe and unsubscribe from the settings page.

I'd say we should go for the full set of these, but feel free to break this down into 3 issues if you think that makes sense. We should prioritize the signup form for before freeze, the following features for Plato.

**Comment by taymonbeal** [comment]
Plato releases during the freeze; those features would have to wait until Aristotle. Are we comfortable getting rid of the registration form checkbox until then?

**Comment by michaltrzesimiech** [comment]
Yes, sure!

**Comment by taymonbeal** [comment]
Split into #648, #649, #650, and #651.
