### ISSUE TITLE
Add a LinkedIn link to profile

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#598]

**Comment by Richenda** [comment]
I would see this as very low priority

**Comment by Richenda** [comment]
I'm worried it would be a lot of work for very little impact

**Comment by michaltrzesimiech** [comment]
I was thinking of adding an optional link to LinkedIn, which isn't much work at all. Also, I see this as potentially very impactful in terms of helping hiring managers use the Hub to find talent.

**Comment by sebgrebe** [comment]
Seconding Michael here, it would be quite good to help EA orgs hiring to find the Linkedin links of members quickly and easily and it is easy to implement

**Comment by michaltrzesimiech** [comment]
Yeah, we should definitely do that. How about we add (to profile) another panel like `Links` and include (optional) links to Facebook and to LinkedIn, and a personal website?

**Comment by taymonbeal** [comment]
Did we decide anything about #337?

**Comment by Richenda** [comment]
> Did we decide anything about #337?

Just that it isn't an immediate priority

**Comment by michaltrzesimiech** [comment]
We should up the priority of this based on multiple prompts, including from organisational users
