### ISSUE TITLE
Handle legacy group URLs

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#604]
This affects the following URLs:
- `/groups/<slug>`

**Comment by taymonbeal** [comment]
Note that this doesn't fully resolve the issue, because many groups are using different slugs now than they were on the old Hub, so those links are still broken. To fully resolve this we need groups to be able to have aliases, like how profiles do today, and we need to import all the old slugs as aliases.

**Comment by victor-yunenko** [comment]
I believe we have another ticket for that which would allow url editing, I'll close this issue for now then.
