### ISSUE TITLE
Handle requests for legacy CSS and JavaScript

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#605]
This affects the following URLs:
- `/sites/eahub.org/files/css/css_[a-zA-Z0-9_-]+\.css`
- `/sites/all/modules/ctools/js/jump-menu.js`
- `/sites/all/modules/google_analytics/googleanalytics.js`
- `/misc/drupal.js`
- `/misc/tableheader.js`
- `/sites/all/modules/captcha/captcha.js`
- `/sites/all/modules/jquery_update/replace/jquery/1.9/jquery.min.js`
- `/sites/all/modules/jquery_update/replace/ui/external/jquery.cookie.js`
- `/misc/jquery.once.js`
- `/sites/all/libraries/chosen/chosen.jquery.min.js`
- `/sites/all/modules/chosen/chosen.js`
- `/sites/all/modules/webform/js/webform.js`

**Comment by victor-yunenko** [comment]
Closing since I'm assuming that the old links have been updated/dropped during the last year. Please feel free to reopen if needed.
