### ISSUE TITLE
Redirect from legacy content URLs

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#609]
This affects the following URLs:
- `/actions/donating`
- `/actions/leaving-money-to-charity-in-your-will`
- `/links`
- `/groups/facebook-invites`
- `/groups/local-group-support-overview-lean-cea-and-eaf`
- `/career-help`
- `/groups/resources/free-meetup-accounts`
- `/groups/resources/giving-games`
- `/actions`
- `/eahub.org/groups/resources/recruiting-managing-members`

**Comment by taymonbeal** [comment]
Also, `/groups/get-a-website`.

**Comment by taymonbeal** [comment]
I need to know where all these URLs should point to.

**Comment by michaltrzesimiech** [comment]
Also: https://github.com/rtcharity/eahub.org/issues/522 https://github.com/rtcharity/eahub.org/issues/520

**Comment by michaltrzesimiech** [comment]
All of the URLs should redirect to the main page. #522 #520 will be created from scratch (one will host the Survey, the other will host the EA Newsletter subscription box).

**Comment by taymonbeal** [comment]
Wait, surely we want this content to still exist somewhere? I had figured it would be on the Resource Trail.

**Comment by michaltrzesimiech** [comment]
We no longer do:
/actions/leaving-money-to-charity-in-your-will
/groups/resources/free-meetup-accounts
/groups/local-group-support-overview-lean-cea-and-eaf

I'd need to look into what these things were, but my guess is that the information there is not up to date:
/actions/donating
/links
/groups/facebook-invites
/career-help
/groups/resources/giving-games
/actions
/eahub.org/groups/resources/recruiting-managing-members

**Comment by taymonbeal** [comment]
Here are some Wayback Machine links:
- https://web.archive.org/web/2017/https://eahub.org/actions/donating
- https://web.archive.org/web/2017/https://eahub.org/actions/leaving-money-to-charity-in-your-will
- https://web.archive.org/web/2017/https://eahub.org/links
- https://web.archive.org/web/2017/https://eahub.org/groups/facebook-invites
- https://web.archive.org/web/2017/https://eahub.org/groups/resources/free-meetup-accounts
- https://web.archive.org/web/2017/https://eahub.org/groups/resources/giving-games
- https://web.archive.org/web/2017/https://eahub.org/actions
- https://web.archive.org/web/2017/https://eahub.org/eahub.org/groups/resources/recruiting-managing-members

They don't have /career-help.

If we've stopped offering a service we should at least put up a page saying what's happened to it. Also, the effective legacies thing seems to have been taken over by Charity Science; we could redirect there.

**Comment by michaltrzesimiech** [comment]
Let's redirect these to resources.eahub.org: 

- /groups/resources/recruiting-managing-members
- /groups/facebook-invites
- /links
- /groups/resources/free-meetup-accounts

I'll have to discuss these with others (but let's redirect to resources.eahub.org ad interim):

- https://web.archive.org/web/20170214090909/https://eahub.org/actions/donating
- https://web.archive.org/web/20170213223518/https://eahub.org/actions

Let's redirect this to https://www.thelifeyoucansave.org/:

- https://web.archive.org/web/20170214050522/https://eahub.org/groups/resources/giving-games

> Also, the effective legacies thing seems to have been taken over by Charity Science; we could redirect there.

Sure, let's (if we have a strong reason to believe this).

**Comment by taymonbeal** [comment]
Do we have specific pages on the resource trail that we can redirect those pages to?

Here are some that might work:

- `/actions/donating` → https://www.givewell.org/charities/top-charities
- `/actions/leaving-money-to-charity-in-your-will` → http://www.charityscience.com/effective-legacies.html
- `/links` → https://resources.eahub.org (temporarily)
- `/groups/facebook-invites` → https://stackoverflow.com/questions/27080936/how-can-i-select-all-friends-in-new-facebook-events-invite-ui#33698935
- `/groups/resources/giving-games` → https://docs.google.com/document/d/1g5G0PvYFs7cAbAZ8ANI_wnsv7DjtBmq4_SQcg44-HDA/edit
- `/actions` → https://www.effectivealtruism.org/get-involved/
- `/eahub.org/groups/resources/recruiting-managing-members` → https://resources.eahub.org/guides_and_tips/tips-from-local-organisers/

Re: free Meetup accounts, we should put up a page somewhere explaining what happened with that program.

Let me know when you figure out what `/groups/local-group-support-overview-lean-cea-and-eaf` and `/career-help` did.

**Comment by michaltrzesimiech** [comment]
Everything looks good, but let's:
- /actions/donating → https://donationswap.eahub.org/charities/

> Re: free Meetup accounts, we should put up a page somewhere explaining what happened with that program.

We could link that and /groups/local-group-support-overview-lean-cea-and-eaf to https://forum.effectivealtruism.org/posts/Cvi7hnTYMk5qutkDg/local-effective-altruism-network-s-new-focus-for-2019

/career-help can be linked to #help-lookingforwork on rtcharity.slack.com.

**Comment by taymonbeal** [comment]
That post doesn't say anything about what happened to the Meetup accounts. Can you maybe leave a comment?

**Comment by taymonbeal** [comment]
Also, Charity Science says they don't want us linking to the effective legacies page. Can we put up some kind of page explaining why this isn't available anymore and what people should do instead?

**Comment by taymonbeal** [comment]
And I need an invite link to that channel; I don't think I can make one myself.

**Comment by michaltrzesimiech** [comment]
I think it's best to either redirect to a mailto: link or put up a page that requests those that are interested to contact us privately for more information. We still manage Meetup accounts though don't want to advertise this. We shouldn't be making annoucnements about RC's offerings (but we could forward emails). 

The link is:
https://join.slack.com/t/rtcharity/shared_invite/enQtMzAyNDgwODAzNjg1LTg5N2Q4YzM4NWZkMDEwYmI5MzY2M2Y2NTI0Yjg0NGNiNjI4MTljZjQxY2IzZjA5NmY0YjA1ZDAxMDA3NDRiYmY

**Comment by taymonbeal** [comment]
We can't redirect to a mailto: link, that doesn't work. Can someone put up a page on the Resource Trail that does the thing we want?

The invite link doesn't seem to point to the right channel.

**Comment by michaltrzesimiech** [comment]
> We can't redirect to a mailto: link, that doesn't work. Can someone put up a page on the Resource Trail that does the thing we want?

We actually have https://resources.eahub.org/contact-lean/

> The invite link doesn't seem to point to the right channel.

I looked into it and it doesn't look like we can get a link for specific channels. People that join will have to navigate on their own (but I should be saying hi to everyone anyway)

**Comment by taymonbeal** [comment]
The thing about these options is that they leave users with no context as to why they got redirected; the pages they wind up on don't have anything to do with the original link. I think we need at least some kind of explanatory message.

**Comment by michaltrzesimiech** [comment]
I'll make sure to post that message today.

**Comment by taymonbeal** [comment]
Moving to Plato because this no longer needs marginal test coverage.

**Comment by taymonbeal** [comment]
Also split off #652 and #653 into separate issues.
