### ISSUE TITLE
Handle requests for legacy images

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#610]
This affects the following URLs:
- `/sites/all/modules/gravatar/avatar-clear.png`
- `/sites/eahub.org/files/default_images/company-big.jpg`
- `/sites/eahub.org/media/images/header-logo-white.png`
- `/img/bg-masthead.png`
- `/static/images/marker.svg`
- `/img/favicons/apple-touch-icon.png`

**Comment by victor-yunenko** [comment]
Closing since I'm assuming that the old links have been updated/dropped during the last year. Please feel free to reopen if needed.
