### ISSUE TITLE
Implement ads.txt

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#614]
This affects the following URLs:
- `/ads.txt`

**Comment by michaltrzesimiech** [comment]
Do we know what was the function of it?

**Comment by taymonbeal** [comment]
Yes, it should be a plain text file with the following contents:

```
placeholder.example.com, placeholder, DIRECT, placeholder
```

**Comment by taymonbeal** [comment]
This indicates to real-time bidding systems that they can't buy or sell any ad inventory on our site.

**Comment by michaltrzesimiech** [comment]
It looks like we don't even need that file after all https://webmasters.stackexchange.com/questions/117761/should-i-publish-an-empty-ads-txt-file-for-a-site-that-does-not-run-any-ads

**Comment by taymonbeal** [comment]
I'm still in favor. It's very straightforward to add (the entire contents of the file are in the above comment) and will keep these queries out of 404 logs.

**Comment by taymonbeal** [comment]
(In general we care more than usual about 404 logs because we broke tons of links rewriting the site and we want to figure out how to unbreak them.)
