### ISSUE TITLE
An organiser can't edit the contents of a group

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#619]
We asked them to try again on a new session, with cookies deleted

**Comment by taymonbeal** [comment]
What error message?

**Comment by michaltrzesimiech** [comment]
I imagine there's no error message. Will have to wait for their response. I copied you in.

**Comment by taymonbeal** [comment]
Reporter could not reproduce. If desired we can open a new issue to make the UI clearer.
