### ISSUE TITLE
Add usernames to names on the lists of names

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#622]
Add usernames to names on the lists of names such as //*[@id="div_id_organisers"]/div/span/div/button so that identical names don't get mixed up

**Comment by taymonbeal** [comment]
I have some doubts as to whether the usernames are actually helpful here; I don't think people think about them much. In cases wherein people genuinely have the same name, some other disambiguator might work better. The more common case is that a single person has multiple accounts, in which case the proper fix is to merge them.

**Comment by taymonbeal** [comment]
Also, you can always hover over the link to see where it points.

**Comment by sebgrebe** [comment]
Any thoughts on @taymonbeal's comments, @michaltrzesimiech? I think he's right, I'm not sure adding usernames adds much value. How were you thinking about adding them? In brackets after the real names? In my case this would read as Sebastian Becker (sebastian-becker), which doesn't look great

Also, to be clear: with list of names you refer to organiser lists on group pages? Assuming from the div id you mention in your comment.

**Comment by michaltrzesimiech** [comment]
> Also, to be clear: with list of names you refer to organiser lists on group pages? Assuming from the div id you mention in your comment.

Yep, that was it.

Having thought about this a bit more, I think you're right. Also, eliminating the need to add organisers manually (which we have in our queue) will sort this out. Let's close the issue for now until it's a bother again.
