### ISSUE TITLE
Prioritize the 404 bugs

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#624]
We probably don't need to fix _all_ of these before the freeze, but we should try to fix some.

Information on the prevalence of each one is available in our Application Insights dashboard.

**Comment by michaltrzesimiech** [comment]
1. Can we make sure that people that try to GET /user/ are being led to /profile/? 
2. Then index.php should be switched with whatever serves the same function in the current setup.
3. Then robots.txt.

**Comment by taymonbeal** [comment]
Yes. To be specific, what I meant was that it would be useful to go through the [comprehensive list of 404 bugs](https://github.com/rtcharity/eahub.org/labels/404) and assign each one to a milestone.

**Comment by taymonbeal** [comment]
(Or note explicitly that something is not a priority and then don't put it on a milestone.)

**Comment by michaltrzesimiech** [comment]
That's done now! Thanks!

**Comment by taymonbeal** [comment]
Moved some of these from End Freeze to Aristotle because they're not freeze-relevant.
