### ISSUE TITLE
Try to make the site load faster

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#625]
It's kind of slow.

**Comment by Manoj-nathwani** [comment]
Can we pass the site through cloudflare so images etc are cached?

**Comment by taymonbeal** [comment]
We could, but we should first figure out where the actual bottlenecks are.

**Comment by ChadoNihi** [comment]
> We could, but we should first figure out where the actual bottlenecks are.

Google's [Lighthouse](https://developers.google.com/web/tools/lighthouse/) (the same as Audits in Chrome's DevTools) or [webhint](https://webhint.io/) can do this. (BTW the former gives 42/100 performance score for the logged out from page, which is considered bad.)

**Comment by victor-yunenko** [comment]
The migration to divio reduced the initial server iresponse time from 2500ms to 500ms, and that's without caching. With caching we should be able to reduce it to 50-100ms. I suspect that Azure hasn't been configured for our django app somehow.

Still even on divio.com the homepage doesn't load all that fast, I suspect that it might be related to the map data being passed as an inlined JSON blob.

**Comment by victor-yunenko** [comment]
Yes, I bet it's about the json blob on the homepage. Hence it would be resolved as part of #976
