### ISSUE TITLE
Control propagation of updates to Python dependencies - eg with pip-compile requirements.txt or Pipfile

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#627]
https://github.com/jazzband/pip-tools might be good for this.

**Comment by taymonbeal** [comment]
This was a cause of #706.

**Comment by taymonbeal** [comment]
This was also a cause of the recent ongoing failures that prevented us from merging PRs or deploying new builds.

**Comment by vagarwalla** [comment]
Update from @victor-yunenko 
- Did not remove the bot
- Removed outdated merge requests
- Victor needs to finish planning & testing the go-live.

**Comment by victor-yunenko** [comment]
Deployed & tested
