### ISSUE TITLE
Forward effectivealtruismhub.org to eahub.org

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#629]
Including both HTTP and email.

**Comment by michaltrzesimiech** [comment]
I've just set up a 301 redirect

**Comment by Manoj-nathwani** [comment]
@michaltrzesimiech It's been 2 days now, this should be working

![image](https://user-images.githubusercontent.com/2634482/56410779-ff63af80-62b0-11e9-847e-85bcc96223a6.png)

**Comment by michaltrzesimiech** [comment]
@jpzg could you help us out with this? I might be doing something wrong, also because I can only work on this through the mobile app

**Comment by jpzg** [comment]
Should emails be forwarded to specific accounts on the eahub.org domain, or should everything go to lean@eahub.org (e.g. should an email to example@effectivealtruismhub.com go to example@eahub.org or lean@eahub.org)? I was looking into how to do this, but having the eahub.org domain under Migadu seems to make it a bit complicated.

**Comment by jpzg** [comment]
@Manoj-nathwani that's because the domain is actually .com, not .org. Which trips me up every time I have to use this domain for anything.

**Comment by jpzg** [comment]
I just replaced the Namecheap redirect with Netlify - Namecheap can't redirect HTTPS requests.
