### ISSUE TITLE
Create manual flow to destroy spam accounts

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#630]
Eventually we will augment this with (outsourced) Fancy Machine Learning, but for the moment we just need the ability for admins to deal with spam as it comes up.

**Comment by Manoj-nathwani** [comment]
We can make a django admin command so through `/admin` we can easily tick off who's clearly made a spam account and create a "disable account" command that'll disable them all.
https://docs.djangoproject.com/en/2.2/howto/custom-management-commands/

**Comment by taymonbeal** [comment]
It's been determined that just deleting them through the admin is sufficient for now.
