### ISSUE TITLE
Integrate donations with PayPal embed

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#637]

**Comment by taymonbeal** [comment]
For Rethink Charity, or for other orgs?

**Comment by Richenda** [comment]
I am totally confused about this ticket

**Comment by michaltrzesimiech** [comment]
Yes, this is for Rethink Charity. Our PayPal allows donors to earmark donations for a specific project (like LEAN/Hub). We already have that, so it's a matter of pasting that embed somewhere, maybe under /about, maybe under a separate site?

**Comment by Richenda** [comment]
> Yes, this is for Rethink Charity. Our PayPal allows donors to earmark donations for a specific project (like LEAN/Hub). We already have that, so it's a matter of pasting that embed somewhere, maybe under /about, maybe under a separate site?

About sounds good if there aren't legal issues with that. In the blurb where we say we have room for funding

**Comment by taymonbeal** [comment]
Can you provide a link? I can also put this in our FUNDING.yml on GitHub, but only if it's earmarked correctly.
