### ISSUE TITLE
EA Hub Settings Menu

### ISSUE THREAD

**Issue by Richenda** [rtcharity/eahub.org#64]
![63e04e02-6730-4625-81a9-169ce9fc8dda](https://user-images.githubusercontent.com/14843012/50624415-d28fb600-0ed4-11e9-95c8-689cfbf206d4.png)

**Comment by michaltrzesimiech** [comment]
@Richenda what should be our priority for this?

**Comment by Richenda** [comment]
Manoj went a different way.

**Comment by michaltrzesimiech** [comment]
Ok, so should we close this? Should I open another ticket i.e. for adding privacy settings? @Richenda

**Comment by michaltrzesimiech** [comment]
@Richenda
