### ISSUE TITLE
Add Mailchimp signup form to site

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#648]
https://github.com/rtcharity/eahub.org/issues/597#issuecomment-485268845

> How should the subscription flow work? The simplest option is to just embed a Mailchimp signup form on our site somewhere.

**Comment by sebgrebe** [comment]
@taymonbeal Could we add the mailchimp URL to the docker environment variables? I was thinking that when running this locally, we don't want the form to be hooked up to the actual mailchimp URL because then we'll add fake users every time we click the submit button locally for testing purposes

**Comment by taymonbeal** [comment]
What would it point to in a local development environment? We don't have a fake Mailchimp that we can add to the docker-compose file.

**Comment by sebgrebe** [comment]
> What would it point to in a local development environment? We don't have a fake Mailchimp that we can add to the docker-compose file.

Ha, literally just wanted to write: Actually, on the other hand, we couldn't model the real behaviour in development then (that is, if we don't want to set up a local API endpoint for the form submit, which seems overkill).

**Comment by sebgrebe** [comment]
should we put a warning there in development that when one adds an email, one should later delete it from mailchimp?
Or should we just not worry about those fake emails?

**Comment by taymonbeal** [comment]
I wouldn't worry about it for now. People can already sign up whenever they want, and I think duplicate signups just get ignored.
