### ISSUE TITLE
Look into defenses against XSS

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#663]
I don't know how to do this in the Django template system. Closure Templates do it well, but the idea of switching to those sounds daunting and also probably introduces compatibility problems with third-party packages.

**Comment by taymonbeal** [comment]
I think this boils down largely to checking for correctly nested quote marks and the like? See also https://security.stackexchange.com/questions/27805/is-djangos-built-in-security-enough.

**Comment by victor-yunenko** [comment]
Yes, django handles it out of the box unless it's disabled intentionally 👌
