### ISSUE TITLE
User couldn't respond to the newsletter message as it points to lean@effectivealtruismhub.com

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#667]
![image](https://user-images.githubusercontent.com/14195560/56899403-a4da0880-6a93-11e9-9da1-7f8e9d799da2.png)

**Comment by michaltrzesimiech** [comment]
We should make sure that responses are forwarded to lean@eahub.org

**Comment by michaltrzesimiech** [comment]
We should also make sure that lean@effectivealtruismhub.com forwards to lean@eahub.org

**Comment by michaltrzesimiech** [comment]
An update: we did receive the message to lean@eahub.org after all. The user received the message from MAILER-DAEMON@aspmx1.migadu.com for an unknown reason. Will have to investigate this.

**Comment by taymonbeal** [comment]
We definitely sent the messages from lean@eahub.org. Are we sure that random people can send mail from there and have it be delivered?

**Comment by taymonbeal** [comment]
Ah, I wonder if the user's email address was a Migadu address?

**Comment by michaltrzesimiech** [comment]
It looks like the user might have had manually edited that address with what he had in his contacts. Tested it on 2 other accounts and there was no similar issue. The actual (though different) issue is https://github.com/rtcharity/eahub.org/issues/629
