### ISSUE TITLE
Migrated links without https:// lead to bad target

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#670]
I.e. this 

![image](https://user-images.githubusercontent.com/14195560/56950549-0ce12b00-6b36-11e9-83d4-1cbcc6503faf.png)

leads to https://eahub.org/group/effective-altruism-turkey/eaturkiye.org

**Comment by taymonbeal** [comment]
Django won't allow users to input invalid links like this; these are left over from the Airtable import. I went into the database and fixed them by hand. Let me know if any more issues are found.
