### ISSUE TITLE
Create missing group profiles based on the Local Groups Survey

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#678]
We want the Local Groups Survey to include an option to start a group profile on the Hub given it doesn't exist for a given group.

**Comment by taymonbeal** [comment]
I still don't feel like I have a very good picture of how we would want any of this to actually work.

**Comment by michaltrzesimiech** [comment]
We need to 
1) ideally: use SurveyMonkey API (https://developer.surveymonkey.com/) to offer an automated creation of user accounts using name, email address and whatever information in the survey itself fits our data model; we will probably have to create an API on the Hub end, so in case LGS can't wait until that's ready, then
2) tactically: take the person that filled in the survey to https://eahub.org/accounts/signup/

**Comment by michaltrzesimiech** [comment]
Continued in this public channel https://rtcharity.slack.com/archives/CHGV507EW/p1557503668020300?thread_ts=1557251179.006200&cid=CHGV507EW
