### ISSUE TITLE
Investigate ways to remediate DEBUG skew

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#688]
The different behavior of the development and production environments can cause unexpected issues like #685. Not sure exactly how to resolve while preserving developer convenience.

**Comment by jpzg** [comment]
Should we create a staging environment as well? It seems to me like the App Service structure makes it straightforward to replicate the production environment, with pretty low cost if we only run it when it's needed.

**Comment by taymonbeal** [comment]
I talked with @michaltrzesimiech about how releases would work, and he was in favor of just pushing everything out to production as soon as it's merged. I think this is probably compatible with a 99% availability SLO, provided that we have a way to quickly roll back bad deployments. So I'm not sure what a staging environment would do in that situation.

**Comment by victor-yunenko** [comment]
Closing as it's been handled within #984
