### ISSUE TITLE
Add ping monitoring

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#689]
So that if the site totally fails to work, like with a bug on the 500 page, we find out about it fast.

**Comment by michaltrzesimiech** [comment]
Done. Added to our Uptime Robot account that will monitor it with the interval of 5 minutes.

**Comment by michaltrzesimiech** [comment]
In case of downtime, we will get notifications also to `admins@eahub.org` and `#rc-tech-alerts`
