### ISSUE TITLE
Stop broken link emails, move the notifications elsewhere

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#691]
i.e. under eahub.org/admin

**Comment by taymonbeal** [comment]
We already have 404 tracking in Azure, though there'll be some false positives there.

**Comment by michaltrzesimiech** [comment]
On second thought, it would be enough and probably easier to just point that email to a dedicated mailbox. In case you agree, I've just created brokenlinks@eahub.org.
