### ISSUE TITLE
Integrate fancy plugin to make nicer town_or_city and country selectors

### ISSUE THREAD

**Issue by Manoj-nathwani** [rtcharity/eahub.org#72]

**Comment by sebgrebe** [comment]
@Manoj-nathwani Do you still want this implemented? If yes, could you give a bit more detail? Not quite sure what you have in mind :)

**Comment by Manoj-nathwani** [comment]
# Problem
At the moment the front-end simply has a text field for filling in both `city/town` & `country`:

![](https://i.imgur.com/xce6pQs.png)

# Solution
It would be really great to get a fancy select box with a search where we already have a list of known `cities/towns` & `countries` so each field can be filled in easier. A little like this:

![](https://i.imgur.com/V26PQT3.png)

This is the [Select2](https://select2.org) plugin which is really great. We should deff use this and pre-load it with all the data from [GeoPy](https://geopy.readthedocs.io/en/stable/) which is what we're using on the backend for location data. It's not super super important to use the same dataset as the backend though.

**Comment by Manoj-nathwani** [comment]
# Problem
At the moment the front-end simply has a text field for filling in both `city/town` & `country`:

![](https://i.imgur.com/xce6pQs.png)

# Solution
It would be really great to get a fancy select box with a search where we already have a list of known `cities/towns` & `countries` so each field can be filled in easier. A little like this:

![](https://i.imgur.com/V26PQT3.png)

This is the [Select2](https://select2.org) plugin which is really great. We should deff use this and pre-load it with all the data from [GeoPy](https://geopy.readthedocs.io/en/stable/) which is what we're using on the backend for location data. It's not super super important to use the same dataset as the backend though.

**Comment by michaltrzesimiech** [comment]
@sebgrebe @Manoj-nathwani prioritizing after the launch, though feel free to adjust as you feel is appropriate
