### ISSUE TITLE
Set up VNC as display manager for selenium tests

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#733]
https://rtcharity.slack.com/archives/CHGV507EW/p1559146368030200

**Comment by victor-yunenko** [comment]
Not sure what this is about exactly - exporting screenshots by the end of a test run?

If yes it would be sure great, but the project is small and we have a lot of other priorities. For the next year I personally would be satisfied with simple HTML validation. After that time we can reopen tickets like that of course.
