### ISSUE TITLE
Group claimed by user with no account (needs investigation)

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#734]
> User (redacted)@gmail.com (about:blank) wants to claim the group EA Toronto (https://eahub.org/group/ea-toronto).  
> Please check whether the user is eligible to claim this group and let them know of the outcome by emailing them at (redacted)@gmail.com.

**Comment by vagarwalla** [comment]
We could not reproduce the issue for EA Toronto & EA Singapore. Now there is a message.
