### ISSUE TITLE
Sometimes, it takes a few times to click a button for it to work 

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#740]
Last valid for the "Edit" button in a group profile.

**Comment by taymonbeal** [comment]
For what it's worth, this has happened to me too.

**Comment by victor-yunenko** [comment]
Sadly it was indeed the case. I was able to reproduce it accidentally and could debug it.

The reason is that our buttons looked as following:
```html
<div class="btn btn-default">
    <a href="{% url 'localgroups_delete' form.instance.slug %}">Delete this group</a>
</div>
```

While it was supposed to be:
```html
<a href="{% url 'localgroups_delete' form.instance.slug %}">
    <div class="btn btn-default">Delete this group</div>
</a>
```

In other words only the inner part of the buttons (the text) were clickable.

**Comment by victor-yunenko** [comment]
deployed and tested 👌
