### ISSUE TITLE
Add Webpack to handle third party JS dependencies

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#744]
We need a little for Google Analytics and Google Maps, but should load it dynamically, probably.

**Comment by sebgrebe** [comment]
We need to add webpack to handle third party JS dependencies, which makes it easier to serve specific versions of them.

Once this is done, we can add further dependencies, needed for the following tickets:
- #764 
- #766 
- #758
- #328 
- #774
