### ISSUE TITLE
Add a couchsurfing box to profile

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#802]
It should say "I may offer a short stay at my place"

**Comment by Richenda** [comment]
How many people actually want this?

**Comment by michaltrzesimiech** [comment]
We never measured this, came as feedback on two, maybe three occasions. Sounds to me like something people might enjoy and use the Hub for.

**Comment by patbl** [comment]
I'll try working on this. Feel free to take over if I haven't posted anything by December 18 (two weeks), or to ask me how it's going if you want it done sooner.

**Comment by patbl** [comment]
Some questions:

* Where should it go on the profile? The most obvious candidates are Community and Summary.
* @michaltrzesimiech, when you say "box," do you mean checkbox? I think this is a good MVP. If people want to add details, they could do so in their profile summary.

**Comment by Richenda** [comment]
Hey I’m on the road tonight but I’ll get a UI answer to you tonight Patrick!

**Comment by Richenda** [comment]
@patbl for public facing display, it should go under the 'Community' section of the profile under the 'available as speaker' section. I would suggest the wording 'open to couchsurfers'. And within the settings for the user it would be a check box also displayed after speaker availability.

**Comment by patbl** [comment]
Thanks! I'll start on this this weekend.
