### ISSUE TITLE
To groups model, add a hidden notes field

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#808]
We've received a request to add a non-public "notes" text field (50,000 characters). By non-public, it means it's editable and viewable by admins only. It should not be available in data exports other than those available to admins (https://github.com/rtcharity/eahub.org/issues/777).

**Comment by cafelow** [comment]
This is now low priority - I couldn't work out how to change the tags

**Comment by cafelow** [comment]
Not required any more.
