### ISSUE TITLE
Feedback: Group page

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#82]
Implements [this wireframe](https://github.com/rtcharity/hubreboot/issues/60)

Some examples:
* [Group with summary; country in key facts](https://eahub.azurewebsites.net/group/96) 
* [Group with summary; organiser and website in key facts](https://eahub.azurewebsites.net/group/97)
* [Group with summary; donations; no key facts](https://eahub.azurewebsites.net/group/116) 
* [Group with more than one organiser in key facts](https://eahub.azurewebsites.net/group/94) 

Remarks
* A couple of fields in the key facts that **were** in the wireframes I didn't implemented as they don't exist in the database
* I've implemented a few fields in the key facts that were **not** in the wireframes, which I implemented as they were in the database and seemed useful 

@Richenda Leave feedback below.

**Comment by Richenda** [comment]
Hey, my comments were all over here: https://github.com/rtcharity/hubreboot/issues/79#issuecomment-452094952
I'll leave this issue open if you prefer to reply to me here. Otherwise close it.

**Comment by michaltrzesimiech** [comment]
@sebgrebe feel free to comment or close whenever you're ready

**Comment by michaltrzesimiech** [comment]
@sebgrebe will close this now
