### ISSUE TITLE
Change eahub.org markup to improve facebook sharing of eahub.org

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#830]
In preparation for sharing widely on facebook!

![image](https://user-images.githubusercontent.com/44737332/66362865-d1019a00-e9e0-11e9-91b4-26dd043bf433.png)

- It would be good if the preview text instead said something other than the code base info. e.g. "Join 2000+ aspiring altruists around the world" will do, but it isn't quite true yet!

- The preview image should be replaced too. The second image in the scroll isn't bad, but it would be best if it appeared first, and ideally had the green backgroup. 

This seems like a good source for information: https://developers.facebook.com/docs/sharing/webmasters

**Comment by victor-yunenko** [comment]
It's a good point that Michal raised in #920, let's move the discussion to that ticket.
