### ISSUE TITLE
Change "Join 2000+ aspiring altruists..."

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#842]
![image](https://user-images.githubusercontent.com/14195560/67835682-dedfa200-faea-11e9-8d2b-47c1a717af42.png)

Change this text to whatever we decide in this thread: https://app.slack.com/client/T07S8FTJQ/CHF7NEM8U

**Comment by sebgrebe** [comment]
Has been postponed until after emails sent to people who filled out EA survey to update afterwards.

**Comment by michaltrzesimiech** [comment]
As of now, we have 805 public profiles. @cafelow I think we're ready to discuss a new slogan for the Hub

**Comment by sebgrebe** [comment]
@cafelow Any thoughts from you on this? The 2000+ seems misleading.

**Comment by cafelow** [comment]
@sebgrebe this is what Michal came up with 
"Do the most good together with the Effective Altruism community"
I like it but I'm not sure if it is grammatically correct! If you think it is okay can you change it?

**Comment by michaltrzesimiech** [comment]
How about we simplify it to "Do the most good with the Effective Altruism community"
