### ISSUE TITLE
Change mentions of lean at eahub.org to contact at eahub.org

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#843]

**Comment by sebgrebe** [comment]
@michaltrzesimiech  Not quite sure what this means. Do you want to replace the "Contact LEAN" buttons on /profiles and /groups to be replaced with "Contact eahub.org"?

**Comment by patbl** [comment]
I can't parse this issue's title in any way other than how you described in (2).

Here's a PR for that interpretation: #857
