### ISSUE TITLE
Change the width of the columns on the speakers and candidate lists

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#854]
Most people's content is far too long for the width. 

It would be also cool to have the first row frozen, so it is still visible when scrolling. 

![image](https://user-images.githubusercontent.com/44737332/69778756-69aade00-120a-11ea-8dd6-bb00328d55ab.png)

**Comment by michaltrzesimiech** [comment]
Highlighting for @sebgrebe
