### ISSUE TITLE
Bug: some font awesome icons are not displaying

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#868]
Groups list:
![Screen Shot 2020-03-01 at 12 58 13](https://user-images.githubusercontent.com/15908208/75626158-e7410a00-5bbc-11ea-9097-facec6d96fe4.png)

**Comment by sebgrebe** [comment]
Message group
![Screen Shot 2020-03-01 at 13 24 22](https://user-images.githubusercontent.com/15908208/75626521-15741900-5bc0-11ea-9b73-e66e2fba8619.png)

**Comment by cafelow** [comment]
I'm not sure the whole column that includes "Page" "Community" "Website" is useful. I think it would be easier (and better) to just delete the column.

**Comment by cafelow** [comment]
Currently "message group" is just a mailto: link (which is more annoying than useful), so until we have messaging available through the Hub, I'd actually like that button to be hidden.
