### ISSUE TITLE
Delete "Community" column on /groups list

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#875]

**Comment by cafelow** [comment]
Is this yet to be deployed?
I notice that while there is no column labelled "community", the "location" column now has the content that used to be under community, and no location. 
![image](https://user-images.githubusercontent.com/44737332/78525482-58fb1c00-782b-11ea-99e2-9dab6ed5710e.png)

**Comment by sebgrebe** [comment]
@cafelow Sorry, you're right. Fixed, I think you should be able to approve the pull request: https://github.com/rtcharity/eahub.org/pull/896. Once it's approved, I can bring the change live
