### ISSUE TITLE
Add option to put name of organiser into "Organiser" /group/* without them being registered

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#880]
There do seem to be people who don't want to join the Hub, but do run groups. Having a name is still useful in those cases. 

This would be something that EA Hub admins would add, or potentially admins of the group would do.

**Comment by sebgrebe** [comment]
Some clarification for developers:  
- The organiser field in localgroups type is linked to profiles class. 
- What we want is that one can also assign a name as organiser, which is not linked to a profile  
- A solution to this might be to introduce a new field in the localgroup type (e.g., "OrganiserFreeText"). This should only be changeable for admins from the admin panel. On the frontend, this should be displayed in addition to the normal organiser field (if not empty), but just as text, not as a link to a profile
