### ISSUE TITLE
Continuous deployment

### ISSUE THREAD

**Issue by taymonbeal** [rtcharity/eahub.org#9]
Changes made to the master branch of this repo on GitHub should automatically be deployed to the staging site.

**Comment by taymonbeal** [comment]
#8 probably needs to happen before this can.

**Comment by taymonbeal** [comment]
Update: We'll continuously deploy directly to production, not staging. The major technical difficulty here is going to be making this work safely with Django migrations.

**Comment by taymonbeal** [comment]
Needs to contain exceptions for vulnerability remediations, but with the same level of review.

**Comment by michaltrzesimiech** [comment]
We now have https://dev.azure.com/eahub/, but we're still configuring it

**Comment by sebgrebe** [comment]
@michaltrzesimiech I'll close this ticket as it needs to be more specific. For example, we could add a "add staging page" ticket. I'm cl
