### ISSUE TITLE
Reorder/rename the links/buttons on the home page

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#901]
The links should start with the Hub things, in order of usefulness. (Gidon suggested we put the resources more prominently... not just me!)

I suggest this order
1. Profiles
2. Resources (okay so I really want Resources first but I'm biased - @michaltrzesimiech might want to weigh in!)
3. Groups
4. Community and Discussion BUT RENAMED TO "Effective Altruism Forum"
5. Then all the rest in the current order is fine.

**Comment by victor-yunenko** [comment]
For now closing in favor of #976 👌
