### ISSUE TITLE
Can "contact us" on the footer have the email address listed?

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#902]
As you know now I'm allergic to mailto: links that masquerade as usual hyperlinks! And I believe I'm not the only person with this particular affiliction!

Currently the footer says
"The codebase of this project is licensed under the MIT License. Post feedback. Privacy Policy. View source. About. Contact us."

Would it be okay to change this to 
"The codebase of this project is licensed under the MIT License. Post feedback. Privacy Policy. View source. About. Contact us by emailing [contact@eahub.org](mailto:contact@eahub.org)."

Is that okay? Too messy?  @michaltrzesimiech?

**Comment by vagarwalla** [comment]
We will address this #1125
