### ISSUE TITLE
Small text changes on /groups/

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#928]
1. Change "create a group" to "register a group" here: https://eahub.org/groups/

2. Above the map have a heading "Directory of Local EA Groups"
Then in regular text:
For non-local groups, head to this list of [groups based on cause-area, career paths, or affiliations](https://resources.eahub.org/learn/connect/).

**Comment by sebgrebe** [comment]
![Screen Shot 2020-05-26 at 13 14 13](https://user-images.githubusercontent.com/15908208/82899407-d6e9c280-9f52-11ea-9dd1-4c6c888840bb.png)
Does this look OK, @cafelow ?

**Comment by cafelow** [comment]
The picture looks great Sebastian!
We should ideally hyperlink all of "list of groups based on cause-area, career paths, or affiliations", as that helps with accessibility (I don't know how many visually impaired people users we have but it is good practice to do best practice especially when it is easy)

**Comment by sebgrebe** [comment]
> it is good practice to do best practice

This seems to be analytically true :)

**Comment by sebgrebe** [comment]
> We should ideally hyperlink all of "list of groups based on cause-area, career paths, or affiliations". 
Done
