### ISSUE TITLE
Cosmetic changes to the landing page

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#940]
On the main page, 

- [ ] remove "EA" from subsite titles 

![image](https://user-images.githubusercontent.com/14195560/85381225-0f72c100-b53e-11ea-8e4f-e0d32eec1c0d.png)

- [ ] Change "High Impact Job Board" to "80,000 Hours Job Board"

![image](https://user-images.githubusercontent.com/14195560/85381334-27e2db80-b53e-11ea-9ff9-a0ee1ef9190a.png)

- [ ] Capitalise "Effective Altruists" in "Join effective altruists [...]" (because we point at members of the movement called Effective Altruism, not necessarily at people who are effective altruists in the literal sense)

![image](https://user-images.githubusercontent.com/14195560/85381615-6e383a80-b53e-11ea-9ef7-76559847414e.png)

- [ ] Increase distance between "Projects" and the map by at least 10 pixels

![image](https://user-images.githubusercontent.com/14195560/85381828-a6d81400-b53e-11ea-8083-f129b5875a29.png)

**Comment by cafelow** [comment]
Related Issue: https://github.com/rtcharity/eahub.org/issues/901

The links should start with the Hub things, in order of usefulness. (Gidon suggested we put the resources more prominently... not just me!)

I suggest this order

Profiles
Resources (okay so I really want Resources first but I'm biased - @michaltrzesimiech might want to weigh in!)
Groups
Community and Discussion BUT RENAMED TO "Effective Altruism Forum"
Then all the rest in the current order is fine.
