### ISSUE TITLE
Add regional level for groups

### ISSUE THREAD

**Issue by cafelow** [rtcharity/eahub.org#941]
1. Please change the group type options to 
City
National/Regional
University

2. I'd ideally like the option for people to share their state. This is only applicable to a couple of countries.
Ideally have a new field "State (if applicable)" - if it is free text then that is okay. 

If it is hard to add another field, we could 
Please change "City or Town" to "City and State (if applicable)"

**Comment by cafelow** [comment]
Any group that is currently listed as "Country" will count as "National".

**Comment by sebgrebe** [comment]
@cafelow the issue with free text fields is that they tend to create a mess. People make typos, use abbreviations or not etc, so this would make the database less reliable, which I think we should avoid. Having a non-free text field will require more work (and I'm not sure right now how we can do that), but if the database should be the "golden source" for local groups, I think it's worth the effort

**Comment by cafelow** [comment]
I understand the messiness. 
From my perspective, I'd still greatly prefer free text than nothing because the city/town doesn't really specify a location (at least in the USA). I'd rather have messy information than incomplete information. 

What I don't understand is how the Hub works out where to put the pin on the map at the moment, so however that works should be preserved (although I had to move a bunch of groups that were located incorrectly when I reviewed all the groups last year, so that process isn't fool proof).

**Comment by michaltrzesimiech** [comment]
But we already have our locations based on free text, no? 

I actually think that implementing this as a list that users could search through might have been an easier way to handle a closed set of locations, but it's probably too much of a hassle to change it on this occasion. 

One way or another, could we tackle this through a hierarchy like:

- National
- Regional (including state)
- City
- University 

This way, we add a new type and we could add logic like: 

if group is national, then show pin around country, 
else if group is regional then show pin around region/state,
else if group is city or university then show pin around city;
else don't show pin (or however we're handling it right now)

If we wanted National/regional, we'd have to have US states represented as "countries". But figuring out the many combinations of that from free text would probably take some sort of suggestions, which isn't trivial to implement.

This might be interesting to us https://stackoverflow.com/a/24871449.

**Comment by cafelow** [comment]
Yeah, I think free text PLUS I get notified whenever a new group is created and I can check it. We only have ~200 groups so new groups don't pop up all that often.

**Comment by sebgrebe** [comment]
Thanks for the input, @cafelow and @michaltrzesimiech 
I conclude that we'll add a free text box which is optional to fill in.

@michaltrzesimiech I don't think there is a need to change how geolocation works. When creating regional/national group, users can continue to enter a city, which makes sense as this would indicate where the "headquarters" or main activity is (AFAIK this hasn't created any controversy so far). The city is what is used by geolocation which makes sense to me. @cafelow this means the existing geolocation will be preserved as asked by you

**Comment by sebgrebe** [comment]
> 
> 
> Yeah, I think free text PLUS I get notified whenever a new group is created and I can check it. We only have ~200 groups so new groups don't pop up all that often.

I just created a [PR for notifications ](https://github.com/rtcharity/eahub.org/pull/952)
