### ISSUE TITLE
Update the list of cause areas

### ISSUE THREAD

**Issue by michaltrzesimiech** [rtcharity/eahub.org#949]
We want the list to fit that used at EAG:

- Building EA Communities
- Psychology Of Decision-making
- Global Priorities Research
- Mental Health/happiness
- Global Health And Development
- Global Coordination/peace-building
- Climate Change
- Ai Strategy And Policy
- Farmed Animal Welfare
- Other Policy Reforms
- Ai Safety Technical Research
- Other Existential Risks
- Wild Animal Welfare
- Biorisk Strategy And Policy
- Information Security
- Quantitative Trading

And keep 

- Long-term Future
- Rationality

We need to migrate the existing

"Global poverty" to "Global Health And Development"
"Cause prioritisation" to "Global Priorities Research"
"Meta" to "Building EA Communities"

**Comment by vagarwalla** [comment]
Hi, quick question on this:
Some of these are not exactly cause areas eg. quantitative trading. Just wondering if it makes sense to include quant tradinging in cause areas, or list it as a profession instead?

**Comment by sebgrebe** [comment]
@vagarwalla Those would probably better fit into the "Areas of Expertise" category

**Comment by vagarwalla** [comment]
**Heres the final request as per the conversation**


We want the list to fit that used at EAG:

- Building EA Communities
- Psychology Of Decision-making
- Global Priorities Research
- Mental Health/Happiness
- Global Health And Development
- Global Coordination/peace-building
- Climate Change
- Farmed Animal Welfare
- Wild Animal Welfare
- Other Policy Reforms
- AI Strategy And Policy
- AI Safety Technical Research
- Other Existential Risks
- Biorisk Strategy And Policy
- Information Security

We will keep:
- Long-term Future
- Rationality

We need to Migrate:

- "Global poverty" to "Global Health And Development"
- "Cause prioritisation" to "Global Priorities Research"
- "Meta" to "Building EA Communities"

**Comment by mattg95** [comment]
A couple of points not covered above:
- Under the new EAG naming, "mental health" will change to  "mental health/happiness"
- Instead of " Animal welfare and rights" we now have "Farmed animal welfare" and "wild animal welfare". I think we should rename " Animal welfare and rights" >>> "Farmed animal welfare" and create "wild animal welfare" as a new topic.  This will affect users that have ticked 'animal welfare and rights' in the past, and the ones from the legacy hub as well
