### ISSUE TITLE
Enable UAT

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#968]
### Current state  
We only have production environment  

Problem: There is no other way to show to product latest developments before deploying other than product running the code locally (which can be quite complicated for a non-tech person) or screenshots. With the work on the enhanced profile directory, this is an impediment to new features being properly tested and getting feedback.  

### Solutions: 
1) Set up a UAT environment, which is accessible to product.  
  - We already have a copy of the prod database set up for this  
  - Cloning the prod app is also quite straightforward with Azure  
  - If I remember correctly, last time the issue we stumbled on was connecting the app and the database   

2) Create new URL for profiles page (where main work will be on) and make it password protected  

#### Risks    
* 1) takes too long  
* 2) not very scalable when working on other parts of page; involves deploying to prod, which could disrupt usage of page if broken code is deployed  

### Acceptance criteria  
Decision made after having discussed with @victor-yunenko

**Comment by victor-yunenko** [comment]
We've schedule a meeting on the next Sunday with Sebastian to look through the options

**Comment by vagarwalla** [comment]
@sebgrebe @victor-yunenko this issue is resolved right?

**Comment by victor-yunenko** [comment]
In general yes, we will need to document it better later on, but that probably should be within a ticket about the readme.
