### ISSUE TITLE
Enhanced profiles search: New profile tiles

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#969]
### Current state  
on the tables in /profiles, each user is just represented as a simple row with 4 columns: image, name, city, country

![image](https://user-images.githubusercontent.com/15908208/93708224-692e5b80-fb2c-11ea-870f-f214cbb363a6.png)

### Desired state  
we have more information on each user  
![image](https://user-images.githubusercontent.com/15908208/93708247-8ebb6500-fb2c-11ea-9fc0-b25b8d4e33e7.png)

### Context
- Dependency: How exactly this will be implemented depends on whether we stick with datatables as our tables plugin or want to to move to something else  
- Implementing "Read more" button is **not** part of this issue  

### Acceptance criteria  
The following information is displayed: 
- [ ] Name: link to profile  
- [ ] Icons representing whether person is available as: volunteer, speaker, employee (ask @vagarwalla: I'm not sure whether this is clear enough in the wireframe. Maybe some text would be clearer?)  
- [ ] City, Country  
- [ ] local group (if any)  
- [ ] local group user is organiser of (if any)  
- [ ] organisation affiliation (if any) 
- [ ] Summary  
- [ ] Areas of experties (empty if none)  
- [ ] cause areas  (empty if none)   

Furthermore:  
- [ ] Design follows wireframe  
- [ ] Is mobile-responsive. Probably best to stack the 4 columns

**Comment by vagarwalla** [comment]
Clarification on Icons:

- Icons will have a transparent background and be GREY by default. If the category applies to a person, the icon will be PURPLE.
- Each icon will have a tooltip. See ammended wireframe.
![image](https://user-images.githubusercontent.com/32846756/93708539-9baa7980-fb69-11ea-800b-7b568d1c3c88.png)

**Comment by victor-yunenko** [comment]
Closing since it's been handled within #958
