### ISSUE TITLE
Enhance user profiles: Multiple fields

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#971]
### Current state  
Users cannot show what they are looking for/can offer to other users (expected for "is available" regarding speaking, volunteering, working)  

### Desired state  
* Users have free text fields where they can share "needs" and "gives"  
* On profiles search, add those lines to tiles. Make searchable

### Context  
This issue blocks #970 

### Acceptance criteria  
- [ ] Needs/gives field added to user model  
- [ ] Needs/gives can be entered in "community" section of profile (check with @vagarwalla whether that's a good solution. Rather than assigning it to "community" it could be edited in the general profile edit page)  
- [ ] Needs/gives is displayed in "community" panel of user profile  (check with @vagarwalla whether that's a good solution. Rather than assigning it to "community" it could be displayed in the general info part of the profile page)

**Comment by vagarwalla** [comment]
- [ ] Add a Forum Profile links in the social media links. Will have the EA logo as the icon that lights up.

**Comment by vagarwalla** [comment]
- To be searchable needs to show up in the cards, otherwise it's confusing where it is
- Join it to the bottom of the summary - not pretty but the text will show up. 

TO-DO
- Add Needs & Gives appended to the bottom of the Summary and fully searchable
