### ISSUE TITLE
Enhanced profiles search: Multiselect boxes

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#972]
### Current state  
On /profiles, users can only search over profiles for limited information (name, city, country)  

### Desired state  
Users can search over all relevant info for users  
![image](https://user-images.githubusercontent.com/15908208/93709207-4f911200-fb34-11ea-98ce-b5d163f8c23b.png)

### Context  
- Filtering will be done on profile tiles, which will be implemented [here](#969). The present ticket is hence blocked by #969  
- How to implement search will depend on which solution we go with for the tables. See discussion [here](https://github.com/rtcharity/eahub.org/issues/958#issuecomment-695766773)  
- This issue is part of several on search functionality

### Acceptance criteria  

- [ ] Multiselect boxes present: City, country, local group, org affiliation, cause area, area of expertise show respectively. (not selected by default)  
- [ ] If I search without having selected, search returns all profiles  
- [ ] If I have selected one option from a multiselect box, it only shows up profiles matching it (e.g., London)  
- [ ] If I have selected multiple options from a multiselect box, it only shows up profiles matching them (e.g., London and Berlin)  
- [ ] Multiselect boxes filter are combined by "AND" logic. I.e., if I put "London" and "CEA", I only get users who live in London and are affiliated with CEA. 

TBD: should we allow for inconsistent inputs, like "London" and "Germany"? Easier to do than implementing some sort of input validation there.  Ask @vagarwalla

**Comment by vagarwalla** [comment]
I think inconsistent filters is fine - worst case scenario nothing pops up. We can do input validation if we get feedback that it's needed.

**Comment by victor-yunenko** [comment]
Closing as part of #958
