### ISSUE TITLE
Enhanced profile search: Toggle boxes  

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#974]
### Current state  
On /profiles, users can only search over profiles for limited information (name, city, country)  

### Desired state  
Users can search over all relevant info for users  
![image](https://user-images.githubusercontent.com/15908208/93709207-4f911200-fb34-11ea-98ce-b5d163f8c23b.png)

### Context  
- Filtering will be done on profile tiles, which will be implemented [here](#969). The present ticket is hence blocked by #969  
- How to implement search will depend on which solution we go with for the tables. See discussion [here](https://github.com/rtcharity/eahub.org/issues/958#issuecomment-695766773)  
- This issue is part of several on search functionality

### Acceptance criteria  
- [ ] Toggle boxes filter profiles by: available as speaker/available as employee/available as volunteer/is group organiser  
- [ ] Toggle boxes are by default unselected. If I search without any selected, I get all profiles   
- [ ] toggle boxes are combined with "AND" logic: if I select "available as speaker" and "group organisers" I only get group organisers that are available as speakers  
- [ ] Wireframe design is implemented  
- [ ] is mobile responsive

**Comment by victor-yunenko** [comment]
Closing since it's been implemented within #958
