### ISSUE TITLE
Enhance profile search: Bring different search modes together

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#975]
### Current state  
On /profiles, users can only search over profiles for limited information (name, city, country)  

### Desired state  
Users can search over all relevant info for users  
![image](https://user-images.githubusercontent.com/15908208/93709207-4f911200-fb34-11ea-98ce-b5d163f8c23b.png)

### Context  
- Filtering will be done on profile tiles, which will be implemented [here](#969). The present ticket is hence blocked by #969  
- How to implement search will depend on which solution we go with for the tables. See discussion [here](https://github.com/rtcharity/eahub.org/issues/958#issuecomment-695766773)  
- This issue brings together the search modes implement in #972, #973, and #974. It is hence blocked by them.     

### Acceptance criteria  
- [ ] The 3 different search modes (search term, multiselect and toggle) work together with "AND" logic. For example, if I enter search term "AI", select "London" and "is available as speaker", I only get profiles who have "AI" in their name or summary, live in London and are available as speakers  
- [ ] Unselecting any of the modes works. For example, when unselecting London in the above example and searching again, I get all profiles who have "AI" in their name or summary and are available as speakers, whereever they live  
- [ ] wireframe design is implemented  
- [ ] is mobile responsive

**Comment by victor-yunenko** [comment]
Closing since it's been implemented within #958
