### ISSUE TITLE
New Homepage (eahub.org)

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#976]
The figma file - https://www.figma.com/file/stekYcAW2fHfIdi6CbY4Li/effective-altruism-hub?node-id=0%3A1

todo:

* [ ] restore a missing profile image
* [ ] test in edge

EA Hub Homepage Design Call Notes - https://docs.google.com/document/d/1J93OP3iI3-oS_18xyUxzjdnOylN8Y39krUbhmUW12LQ/edit

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199874604966892) by [Unito](https://www.unito.io/learn-more)

**Comment by victor-yunenko** [comment]
Thank you for raising this 🙏 !

That was one of the topic that I wanted to bring up at some point - basically our current homepage doesn't really adhere to the landing pages best practices.

Among other things I would like to propose to add a clear CTA along with the description of what the website is about 😅 . We would need to find a good way to put it, in short I mean something similar to:

> Explore and join the effective altruism groups around the world!
> - Create your public profile (CTA primary)
> - Explore EA groups & profile (CTA secondary)

**Comment by vagarwalla** [comment]
Yes I need to work on the CTA & description. See #979 for reference.

**Comment by victor-yunenko** [comment]
The up to date figma file - https://www.figma.com/file/JjIafsXe4fuy5sM2bmsf91/Homepage

The credentials for editing can be provided by me on request.

**Comment by victor-yunenko** [comment]
As I can see the homepage map is loading the data from a JSON plain string rendered in the HTML response. I believe that might be the reason why the homepage response takes 2-3 seconds. I'll try to drop the map and see whether the performance returns to normal.

**Comment by vagarwalla** [comment]
- Haneesha will get back to us with a proposal

**Comment by vagarwalla** [comment]
Update:

- We are using section 1 & 3 of Haneesha's mockup

Text:
**Tagline**
A global directory for effective altruists
Community directory

Below the fold
2 Static screenshots & information
**Groups Directory**
Connect with local, national and virtual groups
**Community Directory**
Search our global directory of thousands of EAs

**Comment by vagarwalla** [comment]
@sebgrebe For the header/footer options: 

Links we need in the main menu

- Donate
- About
- Blog
- "Opportunities Board" eawork.club (external link)
- Resources (External link)

**Comment by victor-yunenko** [comment]
First draft - https://eahub-dev-815fc48.us.aldryn.io/

**Comment by vagarwalla** [comment]
Improvements to Hub homepage:

Add EA work club to menu
![image](https://user-images.githubusercontent.com/32846756/106385917-8d207880-640d-11eb-9926-fe4dc1e35fb2.png)

**Comment by victor-yunenko** [comment]
I see the donation button mention above, but I don't see a link that I can use

**Comment by victor-yunenko** [comment]
@vagarwalla, do you have the link?

**Comment by victor-yunenko** [comment]
@vagarwalla, any update on this?

**Comment by victor-yunenko** [comment]
I guess I'll deploy it tomorrow morning and then we can find the donations link through a separate ticket.

**Comment by victor-yunenko** [comment]
Here's the updated version - https://eahub-dev-815fc48.us.aldryn.io/

**Comment by vagarwalla** [comment]
Final small fixes: 

- [ ] Change community back to Profiles (I'm SO SORRY)

- [ ] Reduce the white space between the header & the first image

![image](https://user-images.githubusercontent.com/32846756/106685080-a2aac380-6602-11eb-984b-f168b2b3d8b0.png)

- [ ] Change the EA Hub Title to Effective Altruism Hub
![image](https://user-images.githubusercontent.com/32846756/106685212-e8678c00-6602-11eb-97bd-4f1b805a76a2.png)

**Comment by victor-yunenko** [comment]
I moved the remaining points to #1148
