### ISSUE TITLE
Analyze the potential competitors of eahub.org to confirm that there's no existing solution on the market

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#977]
I'm creating this ticket after our today's sync with Vaidehi and Sebastian to post the summary:

In short Vaidehi looked through the alternative before for ~half an hour, and today I did a more detailed analysis by spending ~2h.

In short:
- I was looking for social network platforms with group managements & search
- mostly I found immature products, commercial or not

The most probable replacement in the long term I would say is [mastodon](https://github.com/tootsuite/mastodon) (21k stars on github) - but at the moment they don't even have groups, and it'll probably take them 1-3 years to get there since their main goals is to create a social network, but so far they're closer to twitter than facebook.

Few details I left in the spreadsheet, although there's nothing interesting - https://docs.google.com/spreadsheets/d/1eiPa2bF5knKqYj2-UoLx5mMenfqkZeOjpPxBWbHo9y4/edit#gid=0

@vagarwalla, if you could create a public google drive folder where I can drop files of that kind to simplify their sharing - that would be amazing :)

cc @vagarwalla @sebgrebe

**Comment by vagarwalla** [comment]
Here's the folder, it's not public for anyone with link: https://drive.google.com/drive/u/0/folders/1uL1P_rGsaz7Wab3e2QGz3SsG6Lt0Uqvo

**Comment by victor-yunenko** [comment]
Thank you, that looks great 👍 

Could you also add me (victor.yunenko@gmail.com) as an editor to the folder - probably along with other team members - then I can start dropping the files as our comparison spreadsheet in there :)
