### ISSUE TITLE
Update the About Page (eahub.org/about)

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#979]
* Update existing about page to have [this text](https://docs.google.com/document/d/1eJfk5ZkSFuXB0EpQPUb-iRBu3HVsnMnkdFBAtYIn4Zs/edit#)  
* Load github contributors dynamically and display on about page, similar to how it's done [here](https://joshclose.github.io/CsvHelper/)  
* Add a section to readme for contributors, explaining that they will be added to about page as technical contributors once a merge request authored by them goes into main branch  

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199881656165840) by [Unito](https://www.unito.io/learn-more)

**Comment by sebgrebe** [comment]
We're still figuring out a few details in the text, but the ticket is ready to get started on

**Comment by jnsya** [comment]
Note: @sebgrebe @victor-yunenko and I agreed that in this ticket we'll just add the list of contributors as static content, rather than dynamically updated via GitHub, because it's quicker and simpler than connecting to the GitHub API.
