### ISSUE TITLE
Add logging of profile updates, that would allow to analyze the logs in order to assess the profiles activity

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#982]
## Desired state  
Admins can see which actions users have performed at which time. There are two reasons we'd like this feature:  
* To have more data on our user behaviour that we can analyse to improve the page 
* Potentially use this data to indicate to other users how up-to-date a profile is  

## Acceptance criteria  
* Any time a user updates the profile, e.g., changes the summary or adds an organisation they are associated with, save this in a (to be newly created) model  
* Admins can access this information from the admin panel (eahub.org/admin)  
* Information should be filterable by user  
* Information should be orderable by action date  
* Admins can download a csv with that information from the admin panel (similar to groups or profiles)  
* Fields required in new model:  
  * Date of action  
  * User name/profile    
  * Field changes (e.g., summary, city etc)   

## Context/tips  
* Probably best to use post_save functionality of django model (see @victor-yunenko's [comment](https://github.com/rtcharity/eahub.org/issues/982#issuecomment-723595230)   
* Stakeholder: @vagarwalla (PM, has admin rights) asked to be able to see when a user last updated their profile

**Comment by victor-yunenko** [comment]
Better yet - speaking of [our metrics spreadsheet](https://docs.google.com/spreadsheets/d/1erHKaoRalZhWyA9wKIst-cuDMqAfSFHGjkOjayEUT1I/edit#gid=0) - we can log in our database every update of the profile.

Later on in few clicks we export that data in CSV and start building any kind of graph that we want using google sheets 👌

**Comment by sebgrebe** [comment]
@victor-yunenko it seems that your ask is a bit different from @vagarwalla's: 
* Proposal 1:  Add a DateTime field "last_updated" to user model that is updated every time the user makes a change to their profile. Default is the date user's profile was created  
* Proposal 2: Create a table that logs every user action. The field "last_updated" mentioned in Proposal 1 can be inferred from this log table  

Proposal 2 gives us more metrics but takes longer to implement.  

Which one should I implement?

**Comment by victor-yunenko** [comment]
I guess it would be relatively easy, eg a `post_save` signal that calls:
```
UserProfileUpdate.objects.create(
    user=user,
    author=kwargs.get('author'),
)
```

It might be a better idea to store the author since by adding a `last_updated_at` field with an `auto_now=True` kwarg we could accidentally reset that data eg when we run a global python migration or edit somebody in the admin panel. Having an `author` field that would be either `User` or `None` might be of help.

**Comment by victor-yunenko** [comment]
Of course we can also just add a timestamp for now and put the updates model creation into the backlog

**Comment by sebgrebe** [comment]
I would say if @vagarwalla doesn't need the last_updated field immediately, I'm happy to implement the updates model now. Not having looked into this much, I guess I could commit to doing this within the next 2-3 weeks.

**Comment by vagarwalla** [comment]
There's no urgency for this feature! If we do this post MVP, I'd prefer the activity logging one, but only if it's not a lot more effort.

**Comment by sebgrebe** [comment]
@vagarwalla, great, I'll do the activity logging one then
