### ISSUE TITLE
Create a GTM account with custom events

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#983]
The full list of goals can be seen on [the metrics spreadsheet](https://docs.google.com/spreadsheets/d/1erHKaoRalZhWyA9wKIst-cuDMqAfSFHGjkOjayEUT1I/edit#gid=0).

The measures that require an event in GTM are marked with the `GTM` tag.

**Comment by victor-yunenko** [comment]
Hi @taymonbeal, I noticed that you already added GTM, perhaps you could share the access :) ?

**Comment by taymonbeal** [comment]
I didn't add GTM.

**Comment by victor-yunenko** [comment]
we added it
