### ISSUE TITLE
Profile Messaging: Switch messaging on/off in Edit Profile 

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#986]
We need to let users opt in/out of being messaging. 

* Add a checkbox at the bottom of the EA Hub Profile Edit screen (https://eahub.org/profile/edit/) which says : 
"Allow others to message me" [selected by default]
* There will also be a question mark info icon next to it that upon hovering will show a tooltip which says:
"Users will be able to send you messages, which you will receive via email." (wording can change). 
* In Signup flow, add checkbox for "allow others to message me", checked by default
* In email received when user is messaged, add link "change your email preferences", referring to Profile edit
* As part of this ticket, please also change settings so that only approved users can send users a message - at the moment anyone who is logged in, approved or not approved, can send a message

This will replace the "make my email visible":
![image](https://user-images.githubusercontent.com/32846756/96389414-0f2fbd00-11e2-11eb-9000-c937d96d0574.png)

Related issue: #586

┆Issue is synchronized with this [Asana task](https://app.asana.com/0/1199658157929710/1199874607786315) by [Unito](https://www.unito.io/learn-more)

**Comment by sebgrebe** [comment]
Should be on by default

**Comment by sebgrebe** [comment]
> This will replace the "make my email visible":  
@vagarwalla and @victor-yunenko is this true? Victor wrote [here](https://github.com/rtcharity/eahub.org/pull/1095#issuecomment-758165314) that we want to keep email information on user profiles. So in this case we want "allow people messaging me" as an *additional* user setting to "make my email visible".

If we want to keep email info, we need to find a place for the email on the profile. Currently it's only shown on the profiles search. I'd suggest we put it alongside facebook, linkedin etc on the summary tile:

![Uploading image.png…]()


@mattg95 tagging you as you're working on this ticket

**Comment by mattg95** [comment]
Hi, have we reached a decision on @sebgrebe 's point above?

**Comment by sebgrebe** [comment]
@mattg95, let's add "allow users messaging me", rather than it replacing "make my email visible". We can always remove the latter later

**Comment by sebgrebe** [comment]
Acceptance criteria for final UAT  
- [ ] I can send a message to another user who has messaging enabled  
- [ ] The email shows my name, email address, message, link to setting email preferences, link to reporting abuse and link to feedback  
- [ ] I can send a message to a local group where either the local group has an email or organisers who have messaging enabled. The message is sent to all of these available emails
- [ ] The email to groups shows my name, email address, message, link to setting email preferences, link to reporting abuse and link to feedback
- [ ] If a user has not switched on messaging, I cannot send them an email, also not by going on /profile/slug/message
- [ ] If a group has no availability to message them, I cannot send them an email, also not by going on /group/slug/message
- [ ] Messaging to users and individual group organisers is toggled
- [ ] I can set my email preferences
- [ ] My email preferences are by default set to false

**Comment by vagarwalla** [comment]
- [ ] The email icon is still appearing on the main profiles search page & it is a mailto: link, so it look like maybe this was missed? This needs to be fixed - I suggest just having it be purple if the person activated messaging and grey if not - or remove it entirely if that's too complicated right now. I can add it to our post go-live improvements list. 

![image](https://user-images.githubusercontent.com/32846756/106401755-c7ffcc00-6460-11eb-9a24-465a4b91d46b.png)

**Comment by vagarwalla** [comment]
Also this is an unrelated issue, but could we replace the community icon in eahub.org/profiles/xx with a high res image?

![image](https://user-images.githubusercontent.com/32846756/106401903-caaef100-6461-11eb-8892-d541c13a7c9f.png)

**Comment by sebgrebe** [comment]
@vagarwalla, yes, missed the email on search. Good catch! Replaced it with message link

**Comment by sebgrebe** [comment]
> Also this is an unrelated issue, but could we replace the community icon in eahub.org/profiles/xx with a high res image?
See it compared to the career icon below to see the blurriness.  

Good call, done

**Comment by viktor-yunenko** [comment]
@sebgrebe, I believe it was handled? Please feel free to reopen if needed
