### ISSUE TITLE
Delete inactive users

### ISSUE THREAD

**Issue by vagarwalla** [rtcharity/eahub.org#987]
There are several thousand inactive users who didn't reactive their accounts that we need to delete to be compliant with GDPR.

**Comment by sebgrebe** [comment]
I'm not sure how we can distinguish between active and inactive users.

There are approved and unapproved users, but the first unapproved user is from November 2019, all users added prior to this are added, so I don't think this captures those that were added and then didn't active their account.

There is the notion of active users in the admin panel, but *all* our 4000+ users are active. 

I assume @michaltrzesimiech raised this. Did you have an idea of how to distinguish between active and inactive users?
