### ISSUE TITLE
Groups import from Zoho with update & creation of the existing & new groups

### ISSUE THREAD

**Issue by victor-yunenko** [rtcharity/eahub.org#989]
- [x] Victor to provide a CSV file example
- [x] receive the complete CSV data (Catherine hopes to get it somewhere within 1-2 weeks)
- [x] confirm that the email is related to the group only, not the organizers, if that's not the case handle it appropriately (spot check)  
- [x] don't use the `type` field, use only the new `types`
- [x] hide the new export if it isn't completely aligned with the old `export` django action to avoid the potential confusion
- [x] document the existing urls and check that nothing returns 404 errors (solution we eventually went with prevent changing URLs of existing groups that were updated
- [x] import on the stage
- [x] compare the stage to prod (spot check that groups have been updated according to data)  
- [x] ensure that the backup is in place and easily restorable
- [x] ensure that the groups are connected to the organizers manually (spot check)

specs:
- we would need to hide a bunch of groups using the `is_active` flag

**Comment by victor-yunenko** [comment]
Hopefully I'll be able to provide the CSV examples (with & without IDs) sometime over this weekend 👌

**Comment by victor-yunenko** [comment]
Hi @cafelow, btw could you remind me about the deadline just in case?

**Comment by victor-yunenko** [comment]
Hi @cafelow, I implemented the new import. I didn't deploy it yet to the stage server, but here's an example of how an import confirmation could looks like, where I updated an email of a group and added a new one.

I also invited you to the spreadsheet that contains two sheets:
- [exported groups](https://docs.google.com/spreadsheets/d/1QuKuDKYcifYU0VDAzD2HF2G1XVBPT8CLReVC__f5Zqo/edit#gid=2092585553), that can be used as an example of how an import can look like
- [a truncated sheet from the exported group with one new group (without the `id` field)](https://docs.google.com/spreadsheets/d/1QuKuDKYcifYU0VDAzD2HF2G1XVBPT8CLReVC__f5Zqo/edit#gid=1993894235)

![image](https://user-images.githubusercontent.com/36416236/97812733-0df39b00-1c8c-11eb-915f-bf3302667b5f.png)

I also improved the admin panel - added columns, filters and fixed the search:

![image](https://user-images.githubusercontent.com/36416236/97812704-ca992c80-1c8b-11eb-9113-550c8d73fc2c.png)

**Comment by victor-yunenko** [comment]
*the screenshot of the import confirmation was incorrect and didn't contain the email update

**Comment by victor-yunenko** [comment]
FYI I didn't test the import though, only prepared an import spreadsheet example.

**Comment by victor-yunenko** [comment]
It's been also deployed to the stage - https://eahub-stage.us.aldryn.io/admin/localgroups/localgroup/

**Comment by vagarwalla** [comment]
Closing this issue since it was moved to Done by Seb. Please reopen if I'm mistaken.
