### ISSUE TITLE
fix bug with downloading groups in Admin panel

### ISSUE THREAD

**Issue by sebgrebe** [rtcharity/eahub.org#991]

**Comment by cafelow** [comment]
@sebgrebe I'll expect to fix EA Toronto when I'm doing the data update with Victor later this week. Then we don't have to fix the bug.

**Comment by sebgrebe** [comment]
@cafelow This has already been solved for reasons that are not clear to me.
In any case, the bug might reappear with another group, so it's worth fixing

**Comment by sebgrebe** [comment]
this has been done
